pub mod api;
pub mod chain;
pub mod control;
pub mod data;
pub mod files;
pub mod lualib;
pub mod mac;
pub mod media;
pub mod recycle;
pub mod engine;
pub mod sandbox;
pub mod system;

use serde::Serialize;

/// A ready-to-use automation offered on the "New automation" page.
#[derive(Debug, Clone, Serialize)]
pub struct Example {
    pub slug: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub schedule: &'static str,
    pub code: &'static str,
    pub run_on_startup: bool,
    /// Folder to watch ("" for none).
    pub watch_path: &'static str,
    pub watch_pattern: &'static str,
    /// Whether the template needs "Allow system control".
    pub allow_system: bool,
    /// ExtraTriggers as JSON ("" for none).
    pub triggers: &'static str,
}

/// Defaults for the trigger fields, so each template only lists what it uses.
const NO_TRIGGERS: (bool, &str, &str) = (false, "", "");

pub const EXAMPLES: &[Example] = &[
    Example {
        slug: "hello-world",
        title: "Hello world",
        description: "The smallest possible automation. A good place to start.",
        schedule: "",
        code: include_str!("../../scripts/hello_world.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "organize-pdfs",
        title: "Organize PDF files",
        description: "Move PDFs from Downloads into Documents/PDF.",
        schedule: "0 0 * * * *",
        code: include_str!("../../scripts/organize_pdfs.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "tidy-screenshots",
        title: "Tidy screenshots",
        description: "Move screenshots off the Desktop into Pictures/Screenshots.",
        schedule: "0 */30 * * * *",
        code: include_str!("../../scripts/tidy_screenshots.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "backup-notes",
        title: "Back up notes",
        description: "Copy Markdown notes to a backup folder, skipping files already copied.",
        schedule: "0 0 18 * * *",
        code: include_str!("../../scripts/backup_notes.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "open-work-apps",
        title: "Open my work apps",
        description: "Open the apps you use every day in one click, or automatically at sign-in.",
        schedule: "",
        code: include_str!("../../scripts/open_work_apps.lua"),
        run_on_startup: true,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "list-apps",
        title: "List my apps",
        description: "Show the app names app.open() understands, and what's running now.",
        schedule: "",
        code: include_str!("../../scripts/list_apps.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "file-new-pdfs",
        title: "File new PDFs",
        description: "The moment a PDF is downloaded, move it into a Documents/PDF folder for this month.",
        schedule: "",
        code: include_str!("../../scripts/sort_new_pdfs.lua"),
        run_on_startup: false,
        watch_path: "~/Downloads",
        watch_pattern: "*.pdf",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "old-installers",
        title: "Tidy old installers",
        description: "Move installers older than 30 days out of Downloads.",
        schedule: "0 0 10 * * Mon",
        code: include_str!("../../scripts/old_installers.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "largest-files",
        title: "Find the largest files",
        description: "List the 20 biggest files in your home folder (or a whole disk) to free up space.",
        schedule: "",
        code: include_str!("../../scripts/largest_files.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "suspicious-files",
        title: "Look for suspicious files",
        description: "Check file names for signs of malware, like \"trojan\" or fake double extensions. Not an antivirus.",
        schedule: "",
        code: include_str!("../../scripts/suspicious_files.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "low-disk-space",
        title: "Low disk space warning",
        description: "Every hour, warn when a disk has less than 10 GB free.",
        schedule: "0 0 * * * *",
        code: include_str!("../../scripts/low_disk_space.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "clipboard-history",
        title: "Clipboard history",
        description: "Every minute, save new clipboard text to a daily file in Documents.",
        schedule: "0 * * * * *",
        code: include_str!("../../scripts/clipboard_history.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "zip-backup",
        title: "Daily zip backup",
        description: "Every evening, zip your Documents/Notes folder into Backups with today's date.",
        schedule: "0 0 20 * * *",
        code: include_str!("../../scripts/zip_backup.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "wake-every-morning",
        title: "Wake my PC every morning",
        description: "Every evening, set a wake timer so the PC wakes from sleep at 7:30. Needs system control.",
        schedule: "0 0 22 * * *",
        code: include_str!("../../scripts/wake_every_morning.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: true,
        triggers: "",
    },
    Example {
        slug: "focus-mode",
        title: "Focus mode",
        description: "Press Ctrl+Alt+F to close distracting apps and mute the sound. Needs system control.",
        schedule: "",
        code: include_str!("../../scripts/focus_mode.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: true,
        triggers: r#"{"hotkey":"Ctrl+Alt+F"}"#,
    },
    Example {
        slug: "lock-when-idle",
        title: "Lock when I walk away",
        description: "Lock the PC after 10 minutes without keyboard or mouse. Needs system control.",
        schedule: "",
        code: include_str!("../../scripts/lock_when_idle.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: true,
        triggers: r#"{"idle_minutes":10}"#,
    },
    Example {
        slug: "usb-photo-import",
        title: "Import photos from a memory card",
        description: "When a USB drive or card is plugged in, copy its photos into Pictures/Imported.",
        schedule: "",
        code: include_str!("../../scripts/usb_photo_import.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: r#"{"usb":true}"#,
    },
    Example {
        slug: "arrange-windows",
        title: "Arrange my windows",
        description: "Press Ctrl+Alt+A to put your browser on the left and your editor on the right. Needs system control.",
        schedule: "",
        code: include_str!("../../scripts/arrange_windows.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: true,
        triggers: r#"{"hotkey":"Ctrl+Alt+A"}"#,
    },
    Example {
        slug: "find-duplicates",
        title: "Find duplicate files",
        description: "List files with exactly the same contents in Downloads, biggest first, and how much space they waste.",
        schedule: "",
        code: include_str!("../../scripts/find_duplicates.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "shrink-photos",
        title: "Shrink photos for sharing",
        description: "Photos put in Pictures/To share get small copies, quick to send by e-mail or chat.",
        schedule: "",
        code: include_str!("../../scripts/shrink_photos.lua"),
        run_on_startup: false,
        watch_path: "~/Pictures/To share",
        watch_pattern: "*",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "sort-photos-by-date",
        title: "Sort photos by date taken",
        description: "Every evening, move photos from Pictures/Unsorted into year and month folders by when they were taken.",
        schedule: "0 0 20 * * *",
        code: include_str!("../../scripts/sort_photos_by_date.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "webp-to-png",
        title: "Turn WebP downloads into PNG",
        description: "When a .webp picture is downloaded, make a .png copy that every program can open.",
        schedule: "",
        code: include_str!("../../scripts/webp_to_png.lua"),
        run_on_startup: false,
        watch_path: "~/Downloads",
        watch_pattern: "*.webp",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "lock-private-files",
        title: "Lock private files",
        description: "Files put in Documents/Private/To lock are locked with your password. Choose the password in the code first.",
        schedule: "",
        code: include_str!("../../scripts/lock_private_files.lua"),
        run_on_startup: false,
        watch_path: "~/Documents/Private/To lock",
        watch_pattern: "*",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "daily-journal",
        title: "Daily journal page",
        description: "Every morning, create today's journal page in Documents/Journal, ready to write in.",
        schedule: "0 0 7 * * *",
        code: include_str!("../../scripts/daily_journal.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "downloads-report",
        title: "Weekly Downloads report",
        description: "Every Monday, a report and spreadsheet of what fills your Downloads folder.",
        schedule: "0 0 9 * * Mon",
        code: include_str!("../../scripts/downloads_report.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "pc-health",
        title: "PC health check",
        description: "Warn when the processor or memory stays busy, the disk is nearly full or the battery is low.",
        schedule: "0 */15 * * * *",
        code: include_str!("../../scripts/pc_health.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "system-history",
        title: "Daily system history",
        description: "Every night, save the day's CPU, memory, disk and battery history as a spreadsheet.",
        schedule: "0 55 23 * * *",
        code: include_str!("../../scripts/system_history_csv.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "backup-rotation",
        title: "Keep only recent backups",
        description: "Keep the 7 newest backups in ~/Backups; older ones go to the Recycle Bin.",
        schedule: "0 30 20 * * *",
        code: include_str!("../../scripts/backup_rotation.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "website-check",
        title: "Is my website up?",
        description: "Every 10 minutes, check a website and tell you when it goes down and comes back.",
        schedule: "0 */10 * * * *",
        code: include_str!("../../scripts/website_check.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "monthly-expenses",
        title: "Monthly spending summary",
        description: "Add up your spending list (a CSV file) by category, this month next to last month.",
        schedule: "",
        code: include_str!("../../scripts/monthly_expenses.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "date-in-scan-names",
        title: "Put the date in scan names",
        description: "When a scan arrives in Documents/Scans, put the date in front of its name so scans sort nicely.",
        schedule: "",
        code: include_str!("../../scripts/date_in_scan_names.lua"),
        run_on_startup: false,
        watch_path: "~/Documents/Scans",
        watch_pattern: "*.pdf",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "birthday-reminders",
        title: "Birthday reminders",
        description: "Every morning, remind you of birthdays in the next 3 days from a simple list.",
        schedule: "0 0 9 * * *",
        code: include_str!("../../scripts/birthday_reminders.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "clean-temp-files",
        title: "Clean up leftover temp files",
        description: "Every Sunday, move week-old .tmp, .part and unfinished downloads to the Recycle Bin.",
        schedule: "0 0 12 * * Sun",
        code: include_str!("../../scripts/clean_temp_files.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "meeting-mode",
        title: "Meeting mode",
        description: "Press Ctrl+Alt+M to mute, close chat apps and open your meeting app; press again to undo. Needs system control.",
        schedule: "",
        code: include_str!("../../scripts/meeting_mode.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: true,
        triggers: r#"{"hotkey":"Ctrl+Alt+M"}"#,
    },
];

pub fn find_example(slug: &str) -> Option<&'static Example> {
    EXAMPLES.iter().find(|e| e.slug == slug)
}
