pub mod api;
pub mod chain;
pub mod control;
pub mod data;
pub mod files;
pub mod recycle;
pub mod engine;
pub mod sandbox;
pub mod system;

use serde::Serialize;

/// A ready-to-use automation offered on the "New automation" page.
#[derive(Debug, Clone, Serialize)]
pub struct Example {
    pub slug: &'static str,
    pub title: &'static str,
    pub description: &'static str,
    pub schedule: &'static str,
    pub code: &'static str,
    pub run_on_startup: bool,
    /// Folder to watch ("" for none).
    pub watch_path: &'static str,
    pub watch_pattern: &'static str,
    /// Whether the template needs "Allow system control".
    pub allow_system: bool,
    /// ExtraTriggers as JSON ("" for none).
    pub triggers: &'static str,
}

/// Defaults for the trigger fields, so each template only lists what it uses.
const NO_TRIGGERS: (bool, &str, &str) = (false, "", "");

pub const EXAMPLES: &[Example] = &[
    Example {
        slug: "hello-world",
        title: "Hello world",
        description: "The smallest possible automation. A good place to start.",
        schedule: "",
        code: include_str!("../../scripts/hello_world.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "organize-pdfs",
        title: "Organize PDF files",
        description: "Move PDFs from Downloads into Documents/PDF.",
        schedule: "0 0 * * * *",
        code: include_str!("../../scripts/organize_pdfs.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "tidy-screenshots",
        title: "Tidy screenshots",
        description: "Move screenshots off the Desktop into Pictures/Screenshots.",
        schedule: "0 */30 * * * *",
        code: include_str!("../../scripts/tidy_screenshots.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "backup-notes",
        title: "Back up notes",
        description: "Copy Markdown notes to a backup folder, skipping files already copied.",
        schedule: "0 0 18 * * *",
        code: include_str!("../../scripts/backup_notes.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "open-work-apps",
        title: "Open my work apps",
        description: "Open the apps you use every day in one click, or automatically at sign-in.",
        schedule: "",
        code: include_str!("../../scripts/open_work_apps.lua"),
        run_on_startup: true,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "list-apps",
        title: "List my apps",
        description: "Show the app names app.open() understands, and what's running now.",
        schedule: "",
        code: include_str!("../../scripts/list_apps.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "file-new-pdfs",
        title: "File new PDFs",
        description: "The moment a PDF is downloaded, move it into a Documents/PDF folder for this month.",
        schedule: "",
        code: include_str!("../../scripts/sort_new_pdfs.lua"),
        run_on_startup: false,
        watch_path: "~/Downloads",
        watch_pattern: "*.pdf",
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "old-installers",
        title: "Tidy old installers",
        description: "Move installers older than 30 days out of Downloads.",
        schedule: "0 0 10 * * Mon",
        code: include_str!("../../scripts/old_installers.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "largest-files",
        title: "Find the largest files",
        description: "List the 20 biggest files in your home folder (or a whole disk) to free up space.",
        schedule: "",
        code: include_str!("../../scripts/largest_files.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "suspicious-files",
        title: "Look for suspicious files",
        description: "Check file names for signs of malware, like \"trojan\" or fake double extensions. Not an antivirus.",
        schedule: "",
        code: include_str!("../../scripts/suspicious_files.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "low-disk-space",
        title: "Low disk space warning",
        description: "Every hour, warn when a disk has less than 10 GB free.",
        schedule: "0 0 * * * *",
        code: include_str!("../../scripts/low_disk_space.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "clipboard-history",
        title: "Clipboard history",
        description: "Every minute, save new clipboard text to a daily file in Documents.",
        schedule: "0 * * * * *",
        code: include_str!("../../scripts/clipboard_history.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "zip-backup",
        title: "Daily zip backup",
        description: "Every evening, zip your Documents/Notes folder into Backups with today's date.",
        schedule: "0 0 20 * * *",
        code: include_str!("../../scripts/zip_backup.lua"),
        run_on_startup: NO_TRIGGERS.0,
        watch_path: NO_TRIGGERS.1,
        watch_pattern: NO_TRIGGERS.2,
        allow_system: false,
        triggers: "",
    },
    Example {
        slug: "wake-every-morning",
        title: "Wake my PC every morning",
        description: "Every evening, set a wake timer so the PC wakes from sleep at 7:30. Needs system control.",
        schedule: "0 0 22 * * *",
        code: include_str!("../../scripts/wake_every_morning.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: true,
        triggers: "",
    },
    Example {
        slug: "focus-mode",
        title: "Focus mode",
        description: "Press Ctrl+Alt+F to close distracting apps and mute the sound. Needs system control.",
        schedule: "",
        code: include_str!("../../scripts/focus_mode.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: true,
        triggers: r#"{"hotkey":"Ctrl+Alt+F"}"#,
    },
    Example {
        slug: "lock-when-idle",
        title: "Lock when I walk away",
        description: "Lock the PC after 10 minutes without keyboard or mouse. Needs system control.",
        schedule: "",
        code: include_str!("../../scripts/lock_when_idle.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: true,
        triggers: r#"{"idle_minutes":10}"#,
    },
    Example {
        slug: "usb-photo-import",
        title: "Import photos from a memory card",
        description: "When a USB drive or card is plugged in, copy its photos into Pictures/Imported.",
        schedule: "",
        code: include_str!("../../scripts/usb_photo_import.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: false,
        triggers: r#"{"usb":true}"#,
    },
    Example {
        slug: "arrange-windows",
        title: "Arrange my windows",
        description: "Press Ctrl+Alt+A to put your browser on the left and your editor on the right. Needs system control.",
        schedule: "",
        code: include_str!("../../scripts/arrange_windows.lua"),
        run_on_startup: false,
        watch_path: "",
        watch_pattern: "",
        allow_system: true,
        triggers: r#"{"hotkey":"Ctrl+Alt+A"}"#,
    },
];

pub fn find_example(slug: &str) -> Option<&'static Example> {
    EXAMPLES.iter().find(|e| e.slug == slug)
}
