-- Tests for lf.retry, lf.template, lf.report, lf.test itself, and require.
local test = require("lf.test")
local retry = require("lf.retry")
local template = require("lf.template")
local report = require("lf.report")
local paths = require("lf.paths")

test.group("require", function()
    test.case("modules load once", function()
        test.truthy(require("lf.strings") == require("lf.strings"))
    end)
    test.case("unknown modules list the real ones", function()
        test.fails(function() require("socket") end, "lf.strings")
    end)
    test.case("the sandbox stays closed", function()
        test.equal(load, nil)
        test.equal(dofile, nil)
        test.equal(io, nil)
        test.equal(os, nil)
    end)
end)

test.group("retry", function()
    test.case("succeeds after failures", function()
        local tries = 0
        local result = retry.times(3, function()
            tries = tries + 1
            if tries < 3 then error("not yet") end
            return "done"
        end, { wait = 0 })
        test.equal(result, "done")
        test.equal(tries, 3)
    end)
    test.case("gives up with the last error", function()
        local seen = {}
        test.fails(function()
            retry.times(2, function() error("offline", 0) end, {
                wait = 0,
                on_error = function(e, attempt) seen[attempt] = e end,
            })
        end, "failed 2 times; last error: offline")
        test.equal(seen, { "offline", "offline" })
    end)
    test.case("until_ok treats nil as failure", function()
        local n = 0
        test.equal(retry.until_ok(5, function() n = n + 1; return n >= 2 and n end, { wait = 0 }), 2)
    end)
    test.case("wait_for", function()
        test.truthy(retry.wait_for(function() return true end, 0))
        test.falsy(retry.wait_for(function() return false end, 0))
    end)
    test.case("measure returns the result too", function()
        local seconds, a, b = retry.measure(function(x) return x, x * 2 end, 21)
        test.equal(a, 21)
        test.equal(b, 42)
        test.truthy(seconds >= 0)
    end)
    test.case("at_most_every remembers", function()
        test.truthy(retry.at_most_every("warn", 3600))
        test.falsy(retry.at_most_every("warn", 3600))
        test.truthy(retry.at_most_every("other", 3600))
        retry.reset("warn")
        test.truthy(retry.at_most_every("warn", 3600))
    end)
    test.case("try never stops the script", function()
        local ok, message = retry.try(function() error("boom") end)
        test.falsy(ok)
        test.truthy(message:find("boom", 1, true))
        test.equal({ retry.try(function() return 5 end) }, { true, 5 })
    end)
end)

test.group("template", function()
    test.case("values and nested values", function()
        test.equal(template.render("Hi {name}, {user.city}!", { name = "Sam", user = { city = "Oslo" } }), "Hi Sam, Oslo!")
    end)
    test.case("filters chain", function()
        test.equal(template.render("{t|trim|upper}", { t = "  shout " }), "SHOUT")
        test.equal(template.render("{s|size}", { s = 2048 }), "2 KB")
        test.equal(template.render("{p|percent}", { p = 42.4 }), "42%")
        test.equal(template.render("{n|round}", { n = 2.6 }), "3")
    end)
    test.case("fallbacks and missing values", function()
        test.equal(template.render("{who?nobody} {x}", {}), "nobody ")
        test.equal(template.render("{list} items", { list = { 1, 2, 3 } }), "3 items")
    end)
    test.case("literal braces", function()
        test.equal(template.render("{{not}} {v}", { v = 1 }), "{not} 1")
    end)
    test.case("custom filters and unknown ones", function()
        template.filter("shout", function(s) return s .. "!" end)
        test.equal(template.render("{a|shout}", { a = "hey" }), "hey!")
        test.fails(function() template.render("{a|nope}", { a = 1 }) end, "unknown filter")
    end)
    test.case("fields", function()
        test.equal(template.fields("{a} {b|upper} {a} {c?x} {{d}}"), { "a", "b", "c" })
    end)
    test.case("render_file", function()
        local source = paths.join(TEST_DIR, "letter.txt")
        fs.write(source, "Dear {name}")
        local out = paths.join(TEST_DIR, "letter-out.txt")
        test.equal(template.render_file(source, { name = "Kim" }, out), "Dear Kim")
        test.equal(fs.read(out), "Dear Kim")
    end)
end)

test.group("report", function()
    test.case("table columns line up, numbers to the right", function()
        local r = report.new("Sizes")
        r:table({ "File", "MB" }, { { "a.txt", 5 }, { "long-name.bin", 120 } })
        test.equal(r.lines[1], "File           MB")
        test.equal(r.lines[2], "-------------  ---")
        test.equal(r.lines[3], "a.txt            5")
        test.equal(r.lines[4], "long-name.bin  120")
    end)
    test.case("counts and summary", function()
        local r = report.new("Cleanup")
        r:count("moved")
        r:count("moved", 2)
        r:count("skipped")
        r:summary()
        local text = r:text()
        test.truthy(text:find("moved: 3", 1, true), text)
        test.truthy(text:find("skipped: 1", 1, true), text)
        test.truthy(text:find("Cleanup\n=======", 1, true), text)
    end)
    test.case("save and append", function()
        local file = paths.join(TEST_DIR, "report.txt")
        report.new("One"):line("first"):save(file)
        report.new("Two"):item("second"):append_to(file)
        local text = fs.read(file)
        test.truthy(text:find("first", 1, true) and text:find("  • second", 1, true), text)
    end)
end)

test.group("lf.test checks itself", function()
    test.case("equal reports both values", function()
        test.fails(function() test.equal({ 1 }, { 2 }) end, "expected { 2 }, got { 1 }")
    end)
    test.case("near", function()
        test.near(0.1 + 0.2, 0.3)
        test.fails(function() test.near(1, 2) end, "about 2")
    end)
    test.case("fails checks the message", function()
        test.fails(function()
            test.fails(function() error("apple") end, "banana")
        end, "banana")
    end)
end)

test.finish()
