-- Tests for the Rust-powered file and media functions, called from Lua.
-- The runner puts a 40x20 picture at TEST_DIR/picture.png before this runs.
local test = require("lf.test")
local paths = require("lf.paths")

local function at(name)
    return paths.join(TEST_DIR, name)
end

test.group("fs.duplicates", function()
    test.case("finds identical files, ignores the rest", function()
        fs.write(at("dups/a.txt"), "same contents")
        fs.write(at("dups/sub/b.txt"), "same contents")
        fs.write(at("dups/c.txt"), "different!!!!")
        fs.write(at("dups/d.log"), "same contents")
        fs.write(at("dups/empty1.txt"), "")
        fs.write(at("dups/empty2.txt"), "")
        local groups, complete = fs.duplicates(at("dups"), "*.txt")
        test.truthy(complete)
        test.equal(#groups, 1)
        test.equal(groups[1].size, 13)
        test.equal(#groups[1].files, 2)
        test.equal(#groups[1].hash, 64)
        local all = fs.duplicates(at("dups"))
        test.equal(#all[1].files, 3)
    end)
    test.case("missing folder", function()
        test.fails(function() fs.duplicates(at("nope")) end, "directory not found")
    end)
end)

test.group("image", function()
    test.case("info", function()
        local info = image.info(at("picture.png"))
        test.equal(info.width, 40)
        test.equal(info.height, 20)
        test.equal(info.format, "png")
    end)
    test.case("resize keeps the shape and only shrinks", function()
        local out = image.resize(at("picture.png"), at("small/picture.jpg"), 10)
        test.truthy(fs.exists(out))
        local info = image.info(out)
        test.equal({ info.width, info.height, info.format }, { 10, 5, "jpg" })
        local same = image.resize(at("picture.png"), at("big.png"), 400, 400)
        test.equal(image.info(same).width, 40)
    end)
    test.case("convert by extension", function()
        image.convert(at("picture.png"), at("picture.webp"))
        test.equal(image.info(at("picture.webp")).format, "webp")
        image.convert(at("picture.png"), at("picture.bmp"))
        test.equal(image.info(at("picture.bmp")).format, "bmp")
    end)
    test.case("replacing a picture keeps the old one in the Recycle Bin", function()
        image.convert(at("picture.png"), at("again.gif"))
        image.convert(at("picture.png"), at("again.gif"))
        test.truthy(fs.exists(at("again.gif")))
    end)
    test.case("clear errors", function()
        fs.write(at("fake.png"), "not really a picture")
        test.fails(function() image.info(at("fake.png")) end, "not a picture")
        test.fails(function() image.convert(at("picture.png"), at("out.xyz")) end, "picture extension")
        test.fails(function() image.resize(at("picture.png"), at("z.png"), 0) end, "at least 1 pixel")
    end)
    test.case("taken is nil without camera data", function()
        test.equal(image.taken(at("picture.png")), nil)
    end)
end)

test.group("csv", function()
    test.case("write and read back with a header", function()
        local file = at("people.csv")
        csv.write(file, {
            { name = "Ana", city = "Lisbon, PT", age = 31 },
            { name = "Bo", city = 'The "Hague"', age = 45 },
        }, { header = { "name", "city", "age" } })
        local rows = csv.read(file)
        test.equal(#rows, 2)
        test.equal(rows[1], { name = "Ana", city = "Lisbon, PT", age = "31" })
        test.equal(rows[2].city, 'The "Hague"')
    end)
    test.case("lists without a header, other separator", function()
        local file = at("plain.csv")
        csv.write(file, { { 1, "a" }, { 2, "b" } }, { separator = ";" })
        test.equal(fs.read(file), "1;a\n2;b\n")
        test.equal(csv.read(file, { header = false, separator = ";" }), { { "1", "a" }, { "2", "b" } })
    end)
    test.case("bad cells", function()
        test.fails(function() csv.write(at("bad.csv"), { { {} } }) end, "cells must be")
    end)
end)

test.group("crypto", function()
    test.case("round trip", function()
        fs.write(at("secret.txt"), "the plan")
        crypto.encrypt(at("secret.txt"), at("secret.txt.locked"), "correct horse")
        local locked = fs.read(at("secret.txt.locked"))
        test.falsy(locked:find("the plan", 1, true))
        test.equal(locked:sub(1, 8), "LFCRYPT1")
        crypto.decrypt(at("secret.txt.locked"), at("opened.txt"), "correct horse")
        test.equal(fs.read(at("opened.txt")), "the plan")
    end)
    test.case("wrong password and wrong file", function()
        test.fails(function()
            crypto.decrypt(at("secret.txt.locked"), at("x.txt"), "wrong password")
        end, "wrong password")
        test.fails(function()
            crypto.decrypt(at("secret.txt"), at("x.txt"), "correct horse")
        end, "not made by crypto.encrypt")
        test.falsy(fs.exists(at("x.txt")))
    end)
    test.case("safety rules", function()
        test.fails(function() crypto.encrypt(at("secret.txt"), at("s2"), "short") end, "at least 8")
        test.fails(function()
            crypto.encrypt(at("secret.txt"), at("secret.txt"), "long enough pw")
        end, "new name")
        test.equal(fs.read(at("secret.txt")), "the plan")
    end)
    test.case("random passwords", function()
        local a, b = crypto.password(), crypto.password(24)
        test.equal(#a, 16)
        test.equal(#b, 24)
        test.not_equal(a, crypto.password())
    end)
end)

test.group("metrics", function()
    test.case("unknown names are refused", function()
        test.fails(function() metrics.average("gpu") end, "unknown value")
    end)
    test.case("works before the first sample", function()
        local recent = metrics.recent(5)
        test.equal(type(recent), "table")
        local avg = metrics.average("cpu", 5)
        test.truthy(avg == nil or (avg >= 0 and avg <= 100))
    end)
end)

test.finish()
