-- Tests for lf.paths and lf.dates. TEST_DIR is an empty folder scripts may use.
local test = require("lf.test")
local paths = require("lf.paths")
local dates = require("lf.dates")

test.group("paths: taking apart", function()
    test.case("normalize", function()
        test.equal(paths.normalize("C:\\Users\\\\me\\"), "C:/Users/me")
        test.equal(paths.normalize("C:\\"), "C:/")
    end)
    test.case("Windows long paths and network paths", function()
        test.equal(paths.normalize("\\\\?\\C:\\Users\\me\\a.webp"), "C:/Users/me/a.webp")
        test.equal(paths.with_ext("\\\\?\\C:\\Users\\me\\a.webp", "png"), "C:/Users/me/a.png")
        test.equal(paths.normalize("\\\\?\\UNC\\server\\share\\x"), "//server/share/x")
        test.equal(paths.dir("\\\\server\\share\\x.txt"), "//server/share")
        test.equal(paths.join("\\\\?\\C:\\data", "b.txt"), "C:/data/b.txt")
    end)
    test.case("name, dir, ext, stem", function()
        local p = "C:/Photos/2026/cat.final.JPG"
        test.equal(paths.name(p), "cat.final.JPG")
        test.equal(paths.dir(p), "C:/Photos/2026")
        test.equal(paths.ext(p), "jpg")
        test.equal(paths.stem(p), "cat.final")
        test.equal(paths.dir("C:/file.txt"), "C:/")
        test.equal(paths.dir("file.txt"), ".")
    end)
    test.case("no extension", function()
        test.equal(paths.ext("README"), "")
        test.equal(paths.ext(".gitignore"), "")
        test.equal(paths.stem("README"), "README")
    end)
    test.case("parts", function()
        test.equal(paths.parts("C:\\a\\b.txt"), { "C:", "a", "b.txt" })
    end)
    test.case("has_ext ignores case and dots", function()
        test.truthy(paths.has_ext("a.PNG", "jpg", ".png"))
        test.falsy(paths.has_ext("a.gif", "jpg", "png"))
    end)
end)

test.group("paths: building", function()
    test.case("join", function()
        test.equal(paths.join("C:/Users/", "/me", "file.txt"), "C:/Users/me/file.txt")
        test.equal(paths.join("a", "", "b"), "a/b")
    end)
    test.case("with_ext and with_name", function()
        test.equal(paths.with_ext("x/pic.png", "jpg"), "x/pic.jpg")
        test.equal(paths.with_ext("x/pic.png", ".webp"), "x/pic.webp")
        test.equal(paths.with_name("x/pic.png", "other.txt"), "x/other.txt")
        test.equal(paths.with_ext("pic.png", "gif"), "pic.gif")
    end)
    test.case("safe_name", function()
        test.equal(paths.safe_name('Q3: "final"?'), "Q3 - final")
        test.equal(paths.safe_name("CON"), "_CON")
        test.equal(paths.safe_name("..."), "unnamed")
        test.equal(paths.safe_name("a/b", "_"), "a_b")
    end)
    test.case("size_text", function()
        test.equal(paths.size_text(500), "500 bytes")
        test.equal(paths.size_text(1536), "1.5 KB")
        test.equal(paths.size_text(3 * 1024 * 1024), "3 MB")
    end)
    test.case("unique adds a number", function()
        local file = paths.join(TEST_DIR, "notes.txt")
        test.equal(paths.unique(file), file)
        fs.write(file, "1")
        test.equal(paths.unique(file), paths.join(TEST_DIR, "notes (2).txt"))
        fs.write(paths.join(TEST_DIR, "notes (2).txt"), "2")
        test.equal(paths.unique(file), paths.join(TEST_DIR, "notes (3).txt"))
    end)
    test.case("ensure_dir", function()
        local dir = paths.join(TEST_DIR, "a", "b")
        test.equal(paths.ensure_dir(dir), dir)
        test.truthy(fs.is_dir(dir))
    end)
end)

test.group("time.parse and time.make", function()
    test.case("parse common forms", function()
        local t = time.parse("2026-03-15 14:05")
        test.equal(time.format("%Y-%m-%d %H:%M", t), "2026-03-15 14:05")
        test.equal(time.format("%Y-%m-%d", time.parse("2026-03-15")), "2026-03-15")
        test.equal(time.format("%d.%m.%Y", time.parse("15.03.2026", "%d.%m.%Y")), "15.03.2026")
        test.equal(time.parse("not a date"), nil)
    end)
    test.case("make rolls over like a calendar", function()
        test.equal(time.format("%Y-%m-%d", time.make({ year = 2026, month = 1, day = 32 })), "2026-02-01")
        test.equal(time.format("%Y-%m-%d", time.make({ year = 2026, month = 13, day = 1 })), "2027-01-01")
        test.equal(time.format("%Y-%m-%d %H:%M", time.make({ year = 2026, month = 3, day = 1, hour = -1 })), "2026-02-28 23:00")
    end)
end)

test.group("dates", function()
    local base = "2026-01-31 10:30"
    test.case("add_days keeps the time", function()
        test.equal(dates.iso_time(dates.add_days(base, 1)), "2026-02-01 10:30")
        test.equal(dates.iso_time(dates.add_days(base, -31)), "2025-12-31 10:30")
    end)
    test.case("add_months stays in the month", function()
        test.equal(dates.iso(dates.add_months(base, 1)), "2026-02-28")
        test.equal(dates.iso(dates.add_months("2028-01-31", 1)), "2028-02-29")
        test.equal(dates.iso(dates.add_months(base, -2)), "2025-11-30")
        test.equal(dates.iso(dates.add_months(base, 12)), "2027-01-31")
    end)
    test.case("leap years and month lengths", function()
        test.truthy(dates.is_leap_year(2024))
        test.falsy(dates.is_leap_year(1900))
        test.truthy(dates.is_leap_year(2000))
        test.equal(dates.days_in_month(2026, 2), 28)
        test.equal(dates.days_in_month(2024, 2), 29)
    end)
    test.case("start and end of day, week, month", function()
        test.equal(dates.iso_time(dates.start_of_day(base)), "2026-01-31 00:00")
        test.equal(time.format("%H:%M:%S", dates.end_of_day(base)), "23:59:59")
        -- 2026-01-31 is a Saturday; its week starts on Monday the 26th.
        test.equal(dates.iso(dates.start_of_week(base)), "2026-01-26")
        test.equal(dates.iso(dates.start_of_month(base)), "2026-01-01")
    end)
    test.case("days_between", function()
        test.equal(dates.days_between("2026-01-01", "2026-12-31"), 364)
        test.equal(dates.days_between("2026-03-10", "2026-03-01"), -9)
        test.equal(dates.days_between("2026-03-28 23:00", "2026-03-30 01:00"), 2)
    end)
    test.case("weekdays", function()
        test.truthy(dates.is_weekend("2026-01-31"))
        test.truthy(dates.is_weekday("2026-01-30"))
        test.equal(dates.weekday_name("2026-01-26"), "Monday")
        test.truthy(dates.same_day("2026-01-26 01:00", "2026-01-26 23:00"))
    end)
    test.case("ISO week numbers", function()
        test.equal(dates.week_number("2026-01-01"), 1)
        test.equal(dates.week_number("2027-01-01"), 53)
        test.equal(dates.week_number("2026-06-15"), 25)
    end)
    test.case("next_time", function()
        local from = time.parse("2026-05-10 08:00")
        test.equal(dates.iso_time(dates.next_time("07:30", from)), "2026-05-11 07:30")
        test.equal(dates.iso_time(dates.next_time("9:15", from)), "2026-05-10 09:15")
        test.fails(function() dates.next_time("breakfast") end, "07:30")
    end)
    test.case("duration", function()
        test.equal(dates.duration(0), "0 s")
        test.equal(dates.duration(3725), "1 h 2 min 5 s")
        test.equal(dates.duration(90061), "1 d 1 h 1 min 1 s")
    end)
    test.case("ago", function()
        local now = time.parse("2026-05-10 12:00")
        test.equal(dates.ago(now - 10, now), "just now")
        test.equal(dates.ago(now - 300, now), "5 minutes ago")
        test.equal(dates.ago(now - 3 * 86400, now), "3 days ago")
        test.equal(dates.ago(now + 7200, now), "in 2 hours")
        test.equal(dates.ago(now - 400 * 86400, now), "1 year ago")
    end)
    test.case("bad dates are clear errors", function()
        test.fails(function() dates.add_days("someday", 1) end, "is not a date")
    end)
end)

test.finish()
