-- Tests for lf.strings. Run by crates/core/tests/lua_suite.rs.
local test = require("lf.test")
local strings = require("lf.strings")

test.group("trim", function()
    test.case("both ends", function()
        test.equal(strings.trim("  hi there \t\n"), "hi there")
    end)
    test.case("one end", function()
        test.equal(strings.trim_start("  x  "), "x  ")
        test.equal(strings.trim_end("  x  "), "  x")
    end)
    test.case("only spaces", function()
        test.equal(strings.trim("   "), "")
    end)
    test.case("wrong type is a clear error", function()
        test.fails(function() strings.trim(5) end, "must be text")
    end)
end)

test.group("split", function()
    test.case("keeps empty parts", function()
        test.equal(strings.split("a,b,,c", ","), { "a", "b", "", "c" })
    end)
    test.case("plain separators, not patterns", function()
        test.equal(strings.split("1.2.3", "."), { "1", "2", "3" })
        test.equal(strings.split("a%%b", "%%"), { "a", "b" })
    end)
    test.case("multi-character separator", function()
        test.equal(strings.split("x -> y -> z", " -> "), { "x", "y", "z" })
    end)
    test.case("default is comma", function()
        test.equal(strings.split("a,b"), { "a", "b" })
    end)
    test.case("empty separator gives characters", function()
        test.equal(strings.split("añb", ""), { "a", "ñ", "b" })
    end)
    test.case("lines with Windows endings", function()
        test.equal(strings.lines("one\r\ntwo\nthree\n"), { "one", "two", "three" })
    end)
    test.case("words", function()
        test.equal(strings.words("  the quick\tfox "), { "the", "quick", "fox" })
    end)
end)

test.group("searching", function()
    test.case("starts and ends", function()
        test.truthy(strings.starts_with("report.pdf", "rep"))
        test.falsy(strings.starts_with("report.pdf", "pdf"))
        test.truthy(strings.ends_with("report.pdf", ".pdf"))
        test.truthy(strings.ends_with("x", ""))
    end)
    test.case("contains, with and without case", function()
        test.truthy(strings.contains("Invoice March", "March"))
        test.falsy(strings.contains("Invoice March", "march"))
        test.truthy(strings.contains("Invoice March", "march", true))
        test.truthy(strings.contains("a.b", "."))
    end)
    test.case("count", function()
        test.equal(strings.count("banana", "an"), 2)
        test.equal(strings.count("aaaa", "aa"), 2)
        test.equal(strings.count("abc", ""), 0)
    end)
    test.case("replace is plain", function()
        local text, n = strings.replace("1.5 + 2.5", ".", ",")
        test.equal(text, "1,5 + 2,5")
        test.equal(n, 2)
        test.equal((strings.replace("50%", "%", " percent")), "50 percent")
        test.equal((strings.replace("a", "a", "%1")), "%1")
    end)
end)

test.group("shaping", function()
    test.case("length counts characters", function()
        test.equal(strings.length("Grüße"), 5)
        test.equal(strings.length("Привет"), 6)
    end)
    test.case("truncate", function()
        test.equal(strings.truncate("Hello world", 8), "Hello w…")
        test.equal(strings.truncate("short", 10), "short")
        test.equal(strings.truncate("Hello world", 8, "..."), "Hello...")
    end)
    test.case("padding", function()
        test.equal(strings.pad_left("7", 3, "0"), "007")
        test.equal(strings.pad_right("ab", 4), "ab  ")
        test.equal(strings.pad_left("long", 2), "long")
        test.equal(strings.center("hi", 6, "*"), "**hi**")
    end)
    test.case("title and capitalize", function()
        test.equal(strings.title("hello WORLD it's me"), "Hello World It's Me")
        test.equal(strings.capitalize("hello"), "Hello")
    end)
    test.case("slug and snake", function()
        test.equal(strings.slug("  My Holiday Photos! 2026 "), "my-holiday-photos-2026")
        test.equal(strings.snake("Hello World"), "hello_world")
    end)
    test.case("reverse", function()
        test.equal(strings.reverse("abc"), "cba")
        test.equal(strings.reverse("ёж"), "жё")
    end)
    test.case("blank", function()
        test.truthy(strings.is_blank(nil))
        test.truthy(strings.is_blank("  \t"))
        test.falsy(strings.is_blank(" x "))
    end)
    test.case("wrap", function()
        test.equal(strings.wrap("the quick brown fox jumps", 10), "the quick\nbrown fox\njumps")
    end)
    test.case("numbers", function()
        test.equal(strings.number(1234567.891, 2), "1,234,567.89")
        test.equal(strings.number(999), "999")
        test.equal(strings.number(-1000, 0, " "), "-1 000")
    end)
    test.case("email check", function()
        test.truthy(strings.is_email("someone@example.com"))
        test.falsy(strings.is_email("not an email"))
        test.falsy(strings.is_email("a@b"))
    end)
end)

test.finish()
