-- Tests for lf.tables.
local test = require("lf.test")
local tables = require("lf.tables")

local function double(x) return x * 2 end
local function is_even(x) return x % 2 == 0 end

test.group("transforming", function()
    test.case("map passes the index", function()
        test.equal(tables.map({ 1, 2, 3 }, double), { 2, 4, 6 })
        test.equal(tables.map({ "a", "b" }, function(v, i) return v .. i end), { "a1", "b2" })
    end)
    test.case("filter and reject", function()
        test.equal(tables.filter({ 1, 2, 3, 4 }, is_even), { 2, 4 })
        test.equal(tables.reject({ 1, 2, 3, 4 }, is_even), { 1, 3 })
    end)
    test.case("reduce", function()
        test.equal(tables.reduce({ 1, 2, 3 }, function(sum, x) return sum + x end, 0), 6)
    end)
    test.case("find", function()
        local item, index = tables.find({ 5, 8, 9 }, is_even)
        test.equal(item, 8)
        test.equal(index, 2)
        test.equal(tables.find({ 1 }, is_even), nil)
    end)
    test.case("any and all", function()
        test.truthy(tables.any({ 1, 2 }, is_even))
        test.falsy(tables.all({ 1, 2 }, is_even))
        test.truthy(tables.all({}, is_even))
    end)
end)

test.group("looking inside", function()
    test.case("index_of and contains", function()
        test.equal(tables.index_of({ "a", "b" }, "b"), 2)
        test.truthy(tables.contains({ "a" }, "a"))
        test.falsy(tables.contains({ "a" }, "z"))
    end)
    test.case("keys are sorted", function()
        test.equal(tables.keys({ b = 1, a = 2, c = 3 }), { "a", "b", "c" })
        test.equal(tables.values({ b = 1, a = 2 }), { 2, 1 })
    end)
    test.case("count works for any table", function()
        test.equal(tables.count({ a = 1, b = 2, 3 }), 3)
        test.truthy(tables.is_empty({}))
        test.falsy(tables.is_empty({ x = false }))
    end)
end)

test.group("reordering", function()
    test.case("unique keeps the first", function()
        test.equal(tables.unique({ 3, 1, 3, 2, 1 }), { 3, 1, 2 })
    end)
    test.case("reverse", function()
        test.equal(tables.reverse({ 1, 2, 3 }), { 3, 2, 1 })
    end)
    test.case("slice with negative positions", function()
        test.equal(tables.slice({ 1, 2, 3, 4, 5 }, 2, 4), { 2, 3, 4 })
        test.equal(tables.slice({ 1, 2, 3, 4, 5 }, -2), { 4, 5 })
        test.equal(tables.take({ 1, 2, 3 }, 2), { 1, 2 })
        test.equal(tables.take({ 1 }, 5), { 1 })
    end)
    test.case("sort_by does not change the original", function()
        local words = { "ccc", "a", "bb" }
        test.equal(tables.sort_by(words, string.len), { "a", "bb", "ccc" })
        test.equal(tables.sort_by(words, string.len, true), { "ccc", "bb", "a" })
        test.equal(words, { "ccc", "a", "bb" })
    end)
    test.case("group_by and count_by", function()
        local groups = tables.group_by({ 1, 2, 3, 4, 5 }, function(x) return is_even(x) and "even" or "odd" end)
        test.equal(groups, { even = { 2, 4 }, odd = { 1, 3, 5 } })
        test.equal(tables.count_by({ "a", "b", "a" }), { a = 2, b = 1 })
        test.equal(tables.count_by({ "A", "a" }, string.lower), { a = 2 })
    end)
    test.case("chunk and concat", function()
        test.equal(tables.chunk({ 1, 2, 3, 4, 5 }, 2), { { 1, 2 }, { 3, 4 }, { 5 } })
        test.equal(tables.concat({ 1 }, {}, { 2, 3 }), { 1, 2, 3 })
    end)
end)

test.group("copying and comparing", function()
    test.case("merge: later wins, base unchanged", function()
        local base = { a = 1, b = 2 }
        test.equal(tables.merge(base, { b = 3 }, { c = 4 }), { a = 1, b = 3, c = 4 })
        test.equal(base, { a = 1, b = 2 })
    end)
    test.case("deep copy, also with loops", function()
        local original = { list = { 1, 2 } }
        original.self = original
        local copy = tables.copy(original)
        copy.list[1] = 99
        test.equal(original.list[1], 1)
        test.truthy(copy.self == copy)
    end)
    test.case("equal compares contents", function()
        test.truthy(tables.equal({ a = { 1, 2 } }, { a = { 1, 2 } }))
        test.falsy(tables.equal({ a = 1 }, { a = 1, b = 2 }))
        test.truthy(tables.equal(5, 5))
    end)
end)

test.group("numbers", function()
    test.case("sum and average", function()
        test.equal(tables.sum({ 1, 2, 3 }), 6)
        test.equal(tables.sum({ "a", "bbb" }, string.len), 4)
        test.equal(tables.average({ 2, 4 }), 3)
        test.equal(tables.average({}), nil)
    end)
    test.case("min_by and max_by", function()
        test.equal(tables.max_by({ 3, 9, 2 }), 9)
        test.equal(tables.min_by({ "ccc", "a", "bb" }, string.len), "a")
    end)
    test.case("range", function()
        test.equal(tables.range(3), { 1, 2, 3 })
        test.equal(tables.range(0, 10, 5), { 0, 5, 10 })
        test.equal(tables.range(3, 1, -1), { 3, 2, 1 })
    end)
end)

test.case("dump is readable", function()
    local text = tables.dump({ 1, "two", name = "x", nested = { ok = true } })
    test.truthy(text:find('"two"', 1, true), text)
    test.truthy(text:find('name = "x"', 1, true), text)
    test.truthy(text:find("ok = true", 1, true), text)
    local loop = {}
    loop.me = loop
    test.truthy(tables.dump(loop):find("{ ... }", 1, true))
end)

test.finish()
