// Deutsche Übersetzung der Anleitung. Der Lua-Code bleibt gleich, übersetzt sind Kommentare und Meldungen.

import { code, t, tip, warning, type GuideTranslation } from "./blocks";

export const de: GuideTranslation = {
  api: {
    "fs.list": { summary: "Listet die Dateien in einem Ordner auf, deren Namen zum `Muster` passen. `*` steht für beliebig viele Zeichen, `?` für genau eines. Groß- und Kleinschreibung spielt keine Rolle.", returns: "eine Liste vollständiger Dateipfade" },
    "fs.move": { summary: "Verschiebt oder benennt eine Datei um. Ist das `Ziel` ein vorhandener Ordner, behält die Datei ihren Namen. Fehlende Ordner werden angelegt. Überschreibt nie eine vorhandene Datei.", returns: "den neuen Pfad" },
    "fs.copy": { summary: "Kopiert eine Datei. Funktioniert wie `fs.move`, behält aber das Original. Gibt es die Kopie schon, kommt die alte zuerst in den Windows-Papierkorb.", returns: "den Pfad der Kopie" },
    "fs.exists": { summary: "Prüft, ob eine Datei oder ein Ordner existiert.", returns: "`true` oder `false`" },
    "fs.delete": { summary: "Verschiebt eine Datei oder einen Ordner in den Windows-Papierkorb, von wo sie jederzeit wiederhergestellt werden können.", returns: "`true`, wenn etwas gelöscht wurde, `false`, wenn es nicht existierte" },
    "fs.mkdir": { summary: "Legt einen Ordner an, samt fehlender übergeordneter Ordner. Tut nichts, wenn er schon existiert.", returns: "den Pfad des Ordners" },
    "fs.basename": { summary: "Der Dateiname am Ende eines Pfads.", returns: "Text, z. B. `report.pdf`" },
    "fs.join": { summary: "Setzt Ordner- und Dateinamen zu einem Pfad zusammen und fügt die Trennzeichen selbst ein.", returns: "den zusammengesetzten Pfad" },
    "fs.is_dir": { summary: "Prüft, ob ein Pfad ein Ordner ist (und keine Datei).", returns: "`true` oder `false`" },
    "fs.size": { summary: "Die Größe einer Datei in Bytes. Teilen Sie durch `1024 * 1024` für Megabytes.", returns: "eine Anzahl Bytes" },
    "fs.modified": { summary: "Wann eine Datei zuletzt geändert wurde, als Zeitstempel. Vergleichen Sie mit `time.now()`, um alte Dateien zu finden.", returns: "einen Zeitstempel (Sekunden seit 1970)" },
    "app.open": { summary: "Öffnet eine App über ihren Namen im Startmenü (z. B. `\"Spotify\"`), eine Datei oder einen Ordner mit dem passenden Programm, eine Website oder ein Programm über seinen Pfad. `args` ist eine optionale Liste mit Optionen für ein Programm.", returns: "was geöffnet wurde" },
    "app.running": { summary: "Prüft, ob ein Programm läuft. Verwenden Sie den Programmnamen, z. B. `\"Discord\"` oder `\"chrome\"`; Groß-/Kleinschreibung und `.exe` sind egal.", returns: "`true` oder `false`" },
    "app.list": { summary: "Die Namen aller gerade laufenden Programme. Praktisch, um den Namen für `app.running` herauszufinden.", returns: "eine Liste von Namen" },
    "app.shortcuts": { summary: "Die Namen der Apps im Startmenü, also genau die Namen, die `app.open` versteht.", returns: "eine Liste von Namen" },
    "wait": { summary: "Pausiert das Skript. Nützlich zwischen dem Öffnen von Apps. Das ganze Skript muss trotzdem innerhalb seines Zeitlimits (30 Sekunden) fertig werden." },
    "time.now": { summary: "Die aktuelle Zeit als Zeitstempel: eine Anzahl Sekunden, mit der man leicht rechnen kann.", returns: "einen Zeitstempel" },
    "time.format": { summary: "Wandelt einen Zeitstempel in Text um. Beide Angaben sind optional: Standard ist das Muster `%Y-%m-%d %H:%M:%S` und die aktuelle Zeit. `%Y` Jahr, `%m` Monat, `%d` Tag, `%H` Stunde, `%M` Minute, `%A` Wochentag.", returns: "Text, z. B. `2026-09-29 14:05:00`" },
    "time.date": { summary: "Zerlegt eine Zeit in Teile: `year`, `month`, `day`, `hour`, `min`, `sec`, `weekday` (1 = Montag … 7 = Sonntag) und `yday` (Tag im Jahr). Ohne Zeitstempel: jetzt.", returns: "eine Tabelle" },
    "time.today": { summary: "Das heutige Datum als Text, ideal für Ordnernamen.", returns: "Text wie `2026-09-29`" },
    "time.days": { summary: "Rechnet Tage, Stunden oder Minuten in Sekunden um, damit Sie sie mit Zeitstempeln vergleichen können.", returns: "eine Anzahl Sekunden" },
    "fs.read": { summary: "Liest eine ganze Textdatei (bis 10 MB).", returns: "den Text der Datei" },
    "fs.write": { summary: "Erstellt eine Textdatei oder ersetzt ihren Inhalt (die alte Datei kommt in den Windows-Papierkorb). Fehlende Ordner werden angelegt.", returns: "den Pfad der Datei" },
    "fs.append": { summary: "Hängt Text an das Ende einer Datei an (und legt sie bei Bedarf an). Praktisch für eigene Protokolldateien.", returns: "den Pfad der Datei" },
    "fs.rename": { summary: "Benennt eine Datei oder einen Ordner am selben Ort um. `new_name` ist nur ein Name, ohne Ordner. Überschreibt nie.", returns: "den neuen Pfad" },
    "fs.list_dirs": { summary: "Die Ordner direkt in einem Ordner.", returns: "eine Liste von Ordnerpfaden" },
    "fs.find": { summary: "Wie `fs.list`, sucht aber auch in allen Unterordnern. Stoppt beim Zeitlimit des Skripts; das zweite Ergebnis ist dann `false`.", returns: "eine Liste von Dateipfaden und ob die Suche fertig wurde" },
    "fs.largest": { summary: "Die größten Dateien in einem Ordner und allen Unterordnern, die größte zuerst. `count` ist standardmäßig 10. Um eine ganze Festplatte zu durchsuchen, fügen Sie sie (etwa `C:\\`) in den Einstellungen zu den erlaubten Ordnern hinzu und erhöhen Sie das Zeitlimit.", returns: "eine Liste von `{ path = ..., size = ... }` und ob die Suche fertig wurde" },
    "fs.hash": { summary: "Der SHA-256-Fingerabdruck einer Datei. Dateien mit gleichem Fingerabdruck haben denselben Inhalt. Sie können ihn auch bei einem Dienst wie VirusTotal einfügen, um eine Datei zu prüfen.", returns: "64 Hexadezimalzeichen" },
    "zip.create": { summary: "Packt eine Datei, einen Ordner oder eine Liste davon in ein ZIP-Archiv.", returns: "wie viele Dateien hinzugefügt wurden" },
    "zip.extract": { summary: "Entpackt ein ZIP-Archiv in einen Ordner. Ersetzte Dateien kommen in den Windows-Papierkorb, und Archive, die außerhalb dieses Ordners schreiben wollen, werden abgelehnt.", returns: "wie viele Dateien entpackt wurden" },
    "security.scan": { summary: "Sucht nach Dateinamen, die für Schadsoftware typisch sind: Wörter wie `trojan`, `rootkit`, `worm` oder `keylogger`, gefälschte doppelte Endungen wie `invoice.pdf.exe` und Namen von Windows-Systemprogrammen außerhalb des Windows-Ordners. Es werden nur Namen geprüft; das ist kein Virenscanner.", returns: "eine Liste von `{ path = ..., reason = ... }` und ob die Prüfung fertig wurde" },
    "system.disks": { summary: "Ihre Festplatten mit Größe und freiem Speicher in Bytes.", returns: "eine Liste von `{ name, mount, total, free, removable }`" },
    "system.disk_free": { summary: "Freier Speicher in Bytes auf der Festplatte, auf der `path` liegt (ohne Angabe: Ihr Benutzerordner).", returns: "eine Anzahl Bytes" },
    "system.memory": { summary: "Arbeitsspeicher (RAM) in Bytes.", returns: "`{ total, used, free }`" },
    "system.cpu": { summary: "Wie ausgelastet der Prozessor gerade ist, von 0 bis 100. Die Messung dauert einen Sekundenbruchteil.", returns: "einen Prozentwert" },
    "system.battery": { summary: "Der Akkustand eines Laptops. `nil` auf einem PC ohne Akku.", returns: "`{ percent, charging, plugged_in }` oder `nil`" },
    "system.uptime": { summary: "Wie lange der Computer schon läuft, in Sekunden.", returns: "eine Anzahl Sekunden" },
    "system.computer_name": { summary: "Der Name dieses Computers.", returns: "Text" },
    "system.user_name": { summary: "Der Name des Windows-Benutzers.", returns: "Text" },
    "system.os": { summary: "Die Windows-Version.", returns: "Text, z. B. `Windows 11 (26100)`" },
    "clipboard.get": { summary: "Der Text, der gerade in der Zwischenablage ist (was Sie kopiert haben). `nil`, wenn es kein Text ist.", returns: "Text oder `nil`" },
    "clipboard.set": { summary: "Legt Text in die Zwischenablage, bereit zum Einfügen." },
    "ask": { summary: "Zeigt ein Ja/Nein-Fenster und wartet auf Ihre Antwort. Nützlich vor größeren Aktionen. Die Wartezeit zählt zum Zeitlimit.", returns: "`true` für Ja, `false` für Nein" },
    "sound.beep": { summary: "Spielt den Standard-Windows-Ton." },
    "sound.play": { summary: "Spielt eine .wav-Datei im Hintergrund ab." },
    "json.encode": { summary: "Wandelt eine Lua-Tabelle in JSON-Text um, das Format der meisten Webdienste. Mit `true` als `pretty` wird es gut lesbar.", returns: "Text" },
    "json.decode": { summary: "Wandelt JSON-Text in eine Lua-Tabelle um.", returns: "einen Lua-Wert" },
    "http.get": { summary: "Lädt eine Webseite oder fragt einen Webdienst nach Daten. Fehlerseiten stoppen das Skript nicht: Prüfen Sie `ok` oder `status`.", returns: "`{ status, ok, body }`" },
    "http.post": { summary: "Sendet Daten an einen Webdienst, als JSON (`json = tabelle`) oder als Text (`body = \"...\"`). Praktisch für Discord- oder Telegram-Webhooks.", returns: "`{ status, ok, body }`" },
    "store.get": { summary: "Liest einen Wert, den diese Automatisierung in einem früheren Lauf gespeichert hat. Gibt `default` zurück, wenn es keinen gibt. Testläufe beginnen immer mit leerem Speicher.", returns: "den gespeicherten Wert" },
    "store.set": { summary: "Speichert Text, eine Zahl, `true`/`false` oder eine Tabelle, damit der nächste Lauf sie mit `store.get` lesen kann. Jede Automatisierung hat ihren eigenen Speicher." },
    "store.delete": { summary: "Vergisst einen gespeicherten Wert." },
    "log": { summary: "Schreibt eine Zeile in das Protokoll dieser Automatisierung und in die Ausgabe. So sehen Sie, was Ihr Skript tut." },
    "notify": { summary: "Zeigt eine Windows-Benachrichtigung (wenn in den Einstellungen aktiviert) und schreibt sie ins Protokoll." },
    "print": { summary: "Wie `log`, nimmt aber mehrere Werte und setzt einen Tabulator dazwischen." },
    "ctx.name": { summary: "Der Name der laufenden Automatisierung. Verfügbar in `run = function(ctx)`." },
    "ctx.trigger": { summary: 'Wie der Lauf gestartet wurde: `"manual"` (Jetzt ausführen), `"tray"` (Menü im Infobereich), `"schedule"`, `"startup"`, `"watch"` (neue Datei) oder `"test"` (Testlauf).' },
    "ctx.file": { summary: "Für Automatisierungen, die einen Ordner überwachen: der vollständige Pfad der gerade erschienenen Datei. Sonst `nil`." },
    "ctx.id": { summary: "Die Nummer der Automatisierung. `0` bei Testläufen." },
  },

  snippets: {
    "Remember between runs": { title: "Zwischen Läufen merken", description: "Läufe zählen oder den letzten Wert mit store behalten." },
    "Ask before doing it": { title: "Vorher fragen", description: "Zuerst eine Ja/Nein-Frage zeigen." },
    "Largest files": { title: "Größte Dateien", description: "Die größten Dateien in einem Ordner auflisten." },
    "Send a webhook message": { title: "Webhook-Nachricht senden", description: "Eine Nachricht an Discord (oder einen anderen Webhook) schicken." },
    "Warn on low battery": { title: "Bei schwachem Akku warnen", description: "Benachrichtigen, wenn der Laptop-Akku fast leer ist." },
    "Open apps if not running": { title: "Apps öffnen, falls nicht offen", description: "Öffnet eine Liste von Apps und überspringt bereits offene." },
    "Handle the new file": { title: "Neue Datei verarbeiten", description: "Für Automatisierungen, die einen Ordner überwachen: ctx.file verwenden." },
    "Files older than N days": { title: "Dateien älter als N Tage", description: "Findet Dateien, die sich länger nicht geändert haben." },
    "Folder for today": { title: "Ordner für heute", description: "Legt einen Ordner mit dem heutigen Datum an." },
    "Only on weekdays": { title: "Nur werktags", description: "Hört am Samstag und Sonntag gleich auf." },
    "Loop over files": { title: "Dateien durchgehen", description: "Mit jeder passenden Datei etwas tun." },
    "Move without overwriting": { title: "Verschieben ohne Überschreiben", description: "Verschiebt eine Datei nur, wenn das Ziel noch nicht existiert." },
    "Count and notify": { title: "Zählen und melden", description: "Zählt mit und meldet das Ergebnis am Ende." },
    "Name contains a word": { title: "Name enthält ein Wort", description: "Prüft, ob ein Dateiname einen bestimmten Text enthält." },
    "Get the file extension": { title: "Dateiendung ermitteln", description: "Macht aus „photo.JPG“ ein „jpg“." },
    "Sort files by type": { title: "Dateien nach Typ sortieren", description: "Verschiebt Dateien in Ordner, die nach ihrer Endung benannt sind." },
    "Dry run in tests": { title: "Probelauf im Test", description: "Beim Testlauf nur protokollieren, was passieren würde." },
    "Stop early": { title: "Früh aufhören", description: "Verlässt run, wenn es nichts zu tun gibt." },
  },

  lessons: [
    {
      id: "first",
      title: "1. Ihre erste Automatisierung",
      summary: "Wie eine Automatisierung aussieht und wie man sie ausprobiert.",
      blocks: [
        t("Eine Automatisierung ist ein kleines Programm in Lua, einer einfachen Skriptsprache, die in Spielen und Programmen verwendet wird. Jede Automatisierung hat dieselbe Form:"),
        code('automation {\n    name = "Hallo sagen",\n\n    run = function(ctx)\n        log("Hallo, Welt!")\n    end\n}\n'),
        t("`automation { ... }` beschreibt Ihre Automatisierung. `name` ist ihr Name, und `run` ist der Code, der bei jedem Start ausgeführt wird. Alles zwischen `function(ctx)` und dem passenden `end` ist Ihr Programm."),
        t("`log(...)` schreibt eine Zeile in die Ausgabe, damit Sie sehen, was Ihr Skript tut."),
        tip("Klicken Sie bei einem Beispiel auf dieser Seite auf **Im Editor öffnen** und dann auf **Testlauf** (Strg+Enter). Die Ausgabe erscheint unter dem Editor. Gespeichert wird erst, wenn Sie auf „Speichern“ klicken."),
        t("Zeilen, die mit `--` beginnen, sind Kommentare. Lua ignoriert sie, sie sind Notizen für Menschen:"),
        code('-- Diese ganze Zeile ist ein Kommentar\nlog("Das wird ausgeführt") -- dieser Teil ist auch ein Kommentar\n'),
      ],
    },
    {
      id: "values",
      title: "2. Werte und Variablen",
      summary: "Text, Zahlen und wie man ihnen Namen gibt.",
      blocks: [
        t("Eine Variable ist ein Name für einen Wert. Sie wird mit `local` angelegt:"),
        code('local folder = "~/Downloads"\nlocal limit = 10\nlocal enabled = true\n\nlog(folder)\nlog(limit)\n'),
        t("Text (eine sogenannte *Zeichenkette*) steht in doppelten Anführungszeichen, Zahlen nicht. `true` und `false` sind Ja/Nein-Werte. `nil` bedeutet „kein Wert“."),
        t("Text verbinden Sie mit zwei Punkten, `..`:"),
        code('local name = "report"\nlocal file = name .. ".pdf"\nlog("Die Datei heißt " .. file)\n'),
        t("Zahlen funktionieren wie gewohnt: `+ - * /`. Um eine Variable zu ändern, weisen Sie ihr erneut etwas zu (ohne `local`):"),
        code('local count = 0\ncount = count + 1\ncount = count + 1\nlog("Zähler: " .. count)\n'),
        t("Text hat praktische Helfer. Sie werden mit einem Doppelpunkt nach dem Wert geschrieben:"),
        code('local name = "Holiday Photo.JPG"\nlog(name:lower())                 -- holiday photo.jpg\nlog(name:upper())                 -- HOLIDAY PHOTO.JPG\nlog(tostring(name:find("Photo")))  -- wo "Photo" beginnt: 9\nlog(name:sub(1, 7))               -- die ersten 7 Buchstaben: Holiday\n'),
        tip("`tostring(wert)` wandelt alles in Text um, praktisch vor dem Verbinden mit `..`. `lower` und `upper` ändern nur einfache lateinische Buchstaben (keine Umlaute)."),
      ],
    },
    {
      id: "decisions",
      title: "3. Entscheidungen treffen",
      summary: "Code nur ausführen, wenn etwas zutrifft.",
      blocks: [
        t("Mit `if ... then ... end` tun Sie etwas nur dann, wenn eine Bedingung zutrifft:"),
        code('local count = 12\n\nif count > 10 then\n    log("Das sind viele Dateien")\nelseif count > 0 then\n    log("Ein paar Dateien")\nelse\n    log("Keine Dateien")\nend\n'),
        t("Vergleiche: `==` gleich, `~=` ungleich, `<`, `>`, `<=`, `>=`. Kombinieren Sie sie mit `and`, `or` und `not`:"),
        code('local name = "invoice-march.pdf"\n\nif name:find("invoice") and not name:find("draft") then\n    log("Eine endgültige Rechnung")\nend\n'),
        warning("Ein `=` speichert einen Wert, zwei `==` vergleichen. `if count = 3 then` ist ein Fehler; schreiben Sie `if count == 3 then`."),
        t("Vor dem Bearbeiten einer Datei zu prüfen, ob sie existiert, ist eine sehr häufige Entscheidung:"),
        code('if fs.exists("~/Downloads") then\n    log("Der Downloads-Ordner ist da")\nelse\n    log("Kein Downloads-Ordner")\nend\n'),
      ],
    },
    {
      id: "loops",
      title: "4. Listen und Schleifen",
      summary: "Etwas für jede Datei wiederholen.",
      blocks: [
        t("Eine Liste enthält mehrere Werte in geschweiften Klammern. `#liste` sagt Ihnen, wie viele es sind:"),
        code('local fruits = { "Apfel", "Banane", "Kirsche" }\nlog("Ich habe " .. #fruits .. " Früchte")\nlog("Die erste ist " .. fruits[1])\n'),
        t("Um etwas mit jedem Eintrag zu tun, verwenden Sie die Schleife `for ... in ipairs(liste) do ... end`:"),
        code('local fruits = { "Apfel", "Banane", "Kirsche" }\n\nfor index, fruit in ipairs(fruits) do\n    log(index .. ": " .. fruit)\nend\n'),
        t("`fs.list` liefert eine Liste von Dateien, deshalb beginnt fast jede Datei-Automatisierung so. Schreiben Sie `_`, wenn Sie die Nummer nicht brauchen:"),
        code('local files = fs.list("~/Downloads", "*")\nlog("Downloads enthält " .. #files .. " Dateien")\n\nfor _, file in ipairs(files) do\n    log(fs.basename(file))\nend\n'),
        t("Zum Zählen gibt es die Zahlenschleife:"),
        code('for i = 1, 3 do\n    log("Runde " .. i)\nend\n'),
        tip("Auch Schleifen enden mit `end`. Jedes `if`, `for` und `function` braucht sein eigenes `end`."),
      ],
    },
    {
      id: "functions",
      title: "5. Eigene Funktionen",
      summary: "Einem Stück Code einen Namen geben und es wiederverwenden.",
      blocks: [
        t("Eine Funktion ist ein benanntes Stück Code, das Sie oft ausführen können. Definieren Sie sie, bevor Sie sie verwenden:"),
        code('local function greet(person)\n    log("Hallo, " .. person .. "!")\nend\n\ngreet("Anna")\ngreet("Ben")\n'),
        t("Funktionen können mit `return` einen Wert zurückgeben:"),
        code('local function extension(file)\n    return (file:match("%.([^.]+)$") or ""):lower()\nend\n\nlog(extension("photo.JPG"))   -- jpg\nlog(extension("notes.txt"))   -- txt\n'),
        t("`run = function(ctx) ... end` in Ihrer Automatisierung ist selbst eine Funktion. `return` darin beendet den Lauf vorzeitig."),
      ],
    },
    {
      id: "files",
      title: "6. Mit Dateien arbeiten",
      summary: "Pfade, Muster und sicheres Verschieben.",
      blocks: [
        t("Pfade zeigen auf Dateien und Ordner. `~` ist Ihr Benutzerordner, etwa `C:/Users/Sie`, also ist `~/Downloads` Ihr Downloads-Ordner. Auch unter Windows können Sie `/` schreiben."),
        t("`fs.list(ordner, muster)` findet Dateien. Im Muster steht `*` für „beliebig“:"),
        code('log(#fs.list("~/Downloads", "*.pdf") .. " PDFs")\nlog(#fs.list("~/Downloads", "*.zip") .. " ZIP-Dateien")\nlog(#fs.list("~/Downloads", "Screenshot*") .. " Screenshots")\n'),
        t("Ein sicheres Vorgehen beim Verschieben: Zielpfad zusammensetzen, bereits vorhandene Dateien überspringen und protokollieren, was passiert ist."),
        code('automation {\n    name = "PDFs ordnen",\n\n    run = function(ctx)\n        for _, file in ipairs(fs.list("~/Downloads", "*.pdf")) do\n            local target = fs.join("~/Documents/PDF", fs.basename(file))\n\n            if ctx.trigger == "test" then\n                log("Würde verschieben: " .. fs.basename(file))\n            elseif fs.exists(target) then\n                log("Übersprungen (schon vorhanden): " .. fs.basename(file))\n            else\n                fs.move(file, target)\n                log("Verschoben: " .. fs.basename(file))\n            end\n        end\n    end\n}\n'),
        warning("Testläufe ändern Dateien wirklich. Das Beispiel oben prüft `ctx.trigger == \"test\"`, damit ein Testlauf nur protokolliert, was er tun *würde*. Das ist eine gute Gewohnheit für jedes Skript, das verschiebt oder löscht."),
        tip("Skripte können nur Dateien in Ihren erlaubten Ordnern bearbeiten (Ihr Benutzerordner, sofern Sie es nicht in den Einstellungen geändert haben). Das schützt den Rest Ihres Computers."),
      ],
    },
    {
      id: "schedules",
      title: "7. Zeitpläne und Benachrichtigungen",
      summary: "Automatisch ausführen und darüber informiert werden.",
      blocks: [
        t("Wählen Sie über dem Editor einen **Zeitplan**, etwa *Jede Stunde* oder *Werktags um 9:00*, und speichern Sie. LocalFlow führt die Automatisierung dann selbst aus, solange sie aktiv ist und LocalFlow läuft. Wenn Sie das Fenster schließen, arbeitet es im Infobereich weiter (die Symbole neben der Uhr in der Taskleiste)."),
        t("Wenn die Vorgaben nicht passen, wählen Sie **Eigener…** und schreiben einen Cron-Ausdruck. Er hat sechs Teile: Sekunde, Minute, Stunde, Tag, Monat, Wochentag. `*` bedeutet „jede(r)“, `*/15` bedeutet „jede 15.“."),
        code("-- Beispiele (sie gehören in das Feld „Zeitplan“, nicht in den Code):\n--   0 */15 * * * *      alle 15 Minuten\n--   0 30 8 * * *        täglich um 8:30\n--   0 0 20 * * Sun      sonntags um 20:00\n--   0 0 9 1 * *         am 1. jedes Monats um 9:00\n", false),
        t("Mit `notify(...)` erhalten Sie eine Windows-Benachrichtigung. Das ist am Ende eines geplanten Laufs praktisch:"),
        code('local moved = 3 -- angenommen, wir haben 3 Dateien verschoben\nif moved > 0 then\n    notify(moved .. " Dateien verschoben")\nend\n'),
        tip("Schlägt ein geplanter Lauf fehl, zeigt LocalFlow ebenfalls eine Benachrichtigung. Benachrichtigungen schalten Sie in den Einstellungen ein oder aus."),
      ],
    },
    {
      id: "apps",
      title: "8. Apps öffnen",
      summary: "Programme und Websites mit einem Klick starten.",
      blocks: [
        t("`app.open(...)` startet Dinge für Sie. Übergeben Sie den Namen einer App aus dem Startmenü, eine Datei oder einen Ordner, eine Website oder den vollständigen Pfad zu einem Programm:"),
        code('app.open("notepad")\n'),
        code('app.open("Spotify")                        -- Name im Startmenü\napp.open("https://calendar.google.com")    -- Website\napp.open("~/Documents")                    -- Ordner\napp.open("C:/Program Files/App/app.exe")   -- Programm\n', false),
        t("Sie wissen nicht, wie eine App heißt? `app.shortcuts()` listet alle Namen aus Ihrem Startmenü auf:"),
        code('local names = app.shortcuts()\nlog(#names .. " Apps gefunden")\nfor i = 1, math.min(#names, 15) do\n    log(names[i])\nend\n'),
        t("Damit nichts doppelt geöffnet wird, prüfen Sie vorher mit `app.running(name)`. `wait(sekunden)` gibt einer App einen Moment zum Starten, bevor die nächste kommt:"),
        code('local apps = { "notepad" }\n\nfor _, name in ipairs(apps) do\n    if app.running(name) then\n        log(name .. " ist schon offen")\n    else\n        app.open(name)\n        log(name .. " geöffnet")\n        wait(1)\n    end\nend\n'),
        tip("**Alles bei der Anmeldung öffnen:** Aktivieren Sie über dem Editor **Beim Start von LocalFlow ausführen** und schalten Sie **Einstellungen › Mit Windows starten** ein. Oder klicken Sie mit der rechten Maustaste auf das LocalFlow-Symbol im Infobereich (neben der Uhr in der Taskleiste; klicken Sie auf ^, falls es nicht zu sehen ist) › **Ausführen**, um jede Automatisierung mit einem Klick zu starten."),
        t("Die Vorlage *Meine Arbeits-Apps öffnen* erledigt all das. Ändern Sie einfach die Liste der Namen."),
      ],
    },
    {
      id: "time",
      title: "9. Datum und Uhrzeit",
      summary: "Heutiges Datum, Alter von Dateien und Wochentage.",
      blocks: [
        t("Zeiten sind in LocalFlow *Zeitstempel*: Anzahlen von Sekunden. Damit lässt sich leicht rechnen. `time.now()` ist die aktuelle Zeit:"),
        code('local now = time.now()\nlog("Sekunden seit 1970: " .. now)\nlog("In einer Stunde: " .. time.format("%H:%M", now + time.hours(1)))\n'),
        t("`time.format(...)` macht aus einem Zeitstempel lesbaren Text. `%Y` ist das Jahr, `%m` der Monat, `%d` der Tag, `%H:%M` die Uhrzeit und `%A` der Wochentag (auf Englisch):"),
        code('log(time.format())                   -- 2026-09-29 14:05:00\nlog(time.format("%d.%m.%Y"))         -- 29.09.2026\nlog(time.format("%A"))               -- Tuesday\nlog("Heute ist " .. time.today())    -- 2026-09-29\n'),
        t("`time.date()` zerlegt die Zeit in Teile, die Sie prüfen können, etwa `weekday` (1 = Montag, 7 = Sonntag):"),
        code('local d = time.date()\nif d.weekday >= 6 then\n    log("Wochenende!")\nelseif d.hour < 12 then\n    log("Guten Morgen")\nelse\n    log("Guten Tag")\nend\n'),
        t("`fs.modified(datei)` sagt Ihnen, wann eine Datei zuletzt geändert wurde. Zusammen mit `time.days(n)` finden Sie so alte Dateien:"),
        code('local cutoff = time.now() - time.days(30)\nlocal old = 0\n\nfor _, file in ipairs(fs.list("~/Downloads", "*")) do\n    if fs.modified(file) < cutoff then\n        old = old + 1\n    end\nend\n\nlog(old .. " Dateien in Downloads sind älter als 30 Tage")\n'),
      ],
    },
    {
      id: "watch",
      title: "10. Auf neue Dateien reagieren",
      summary: "Ausführen, sobald eine Datei in einem Ordner landet.",
      blocks: [
        t("Statt nach Zeitplan kann eine Automatisierung auf neue Dateien warten. Aktivieren Sie **Ausführen, wenn eine neue Datei in einem Ordner erscheint**, wählen Sie den Ordner (etwa `~/Downloads`) und optional die Dateien (etwa `*.pdf`)."),
        t("Jedes Mal, wenn eine passende Datei erscheint, läuft Ihre Automatisierung einmal, und `ctx.file` enthält den Pfad der neuen Datei. LocalFlow wartet, bis der Download fertig ist."),
        code('automation {\n    name = "Neue PDFs ablegen",\n\n    run = function(ctx)\n        if not ctx.file then\n            log("Keine neue Datei. Das läuft, sobald eine PDF erscheint.")\n            return\n        end\n\n        local folder = fs.join("~/Documents/PDF", time.format("%Y-%m"))\n        fs.move(ctx.file, fs.join(folder, fs.basename(ctx.file)))\n        notify(fs.basename(ctx.file) .. " abgelegt")\n    end\n}\n'),
        tip("Bei einem **Testlauf** gibt es keine neue Datei, deshalb ist `ctx.file` dann `nil`. Darum prüft das Beispiel das zuerst. Um es wirklich arbeiten zu sehen, speichern Sie und legen Sie eine Datei in den Ordner."),
        warning("Verschieben Sie keine Dateien *in* den überwachten Ordner. Das zählt als neue Datei und startet die Automatisierung erneut."),
      ],
    },
    {
      id: "errors",
      title: "11. Wenn etwas schiefgeht",
      summary: "Fehlermeldungen lesen und beheben.",
      blocks: [
        t("Fehler sehen so aus: `automation:5: attempt to call a nil value`. Die Zahl nach `automation:` ist die **Zeile**, in der es schiefging. Syntaxfehler markiert der Editor schon beim Tippen mit einem roten Punkt."),
        t("Unter häufigen Fehlern zeigt LocalFlow einen 💡-Hinweis. Die üblichen Verdächtigen:"),
        t("• **Fehlendes `end`**: jedes `if`, `for` und `function` braucht eines.\n• **Tippfehler**: `fs.lsit` statt `fs.list` oder `Log` statt `log` (Groß-/Kleinschreibung zählt).\n• **Mit nichts verbinden**: `\"Text\" .. x` scheitert, wenn `x` `nil` ist. Prüfen Sie, ob die Variable einen Wert hat.\n• **Fehlende Anführungszeichen**: Text steht in `\"doppelten Anführungszeichen\"`."),
        t("Wenn Sie nicht sicher sind, was in einer Variablen steht, protokollieren Sie sie:"),
        code('local files = fs.list("~/Downloads", "*.pdf")\nlog("Dateien: " .. #files)\nlog("erste: " .. tostring(files[1]))\n'),
        tip("Jeder Lauf wird im **Verlauf** mit Ausgabe und Fehler gespeichert, und das **Protokoll** zeigt alles, was Ihre Automatisierung geschrieben hat."),
      ],
    },
    {
      id: "tools",
      title: "12. Weitere Werkzeuge und Teilen",
      summary: "Speicher, Fragen, Systeminfos, das Web und Automatisierungen teilen.",
      blocks: [
        t("**Sich etwas merken.** Variablen gehen am Ende eines Laufs verloren. `store.set(schlüssel, wert)` speichert einen Wert für den nächsten Lauf, und `store.get(schlüssel, standard)` liest ihn wieder. (Testläufe beginnen immer mit leerem Speicher.)"),
        code('local runs = store.get("runs", 0) + 1\nstore.set("runs", runs)\nlog("Diese Automatisierung ist " .. runs .. "-mal gelaufen")\n'),
        t("**Erst fragen.** `ask(frage)` zeigt ein Ja/Nein-Fenster und wartet auf Ihre Antwort:"),
        code('if ask("Hallo sagen?") then\n    log("Hallo!")\nelse\n    log("OK, vielleicht später")\nend\n'),
        t("**Ihr Computer.** Die `system`-Funktionen verraten Ihnen etwas über Festplatten, Arbeitsspeicher, Akku und mehr:"),
        code('local gb = 1024 * 1024 * 1024\nlog("Computer: " .. system.computer_name())\nlog("Frei auf Ihrer Festplatte: " .. math.floor(system.disk_free() / gb) .. " GB")\nlocal m = system.memory()\nlog("Arbeitsspeicher belegt: " .. math.floor(m.used / m.total * 100) .. "%")\n'),
        t("**Textdateien und JSON.** `fs.write`, `fs.append` und `fs.read` arbeiten mit Textdateien. `json.encode` und `json.decode` wandeln zwischen Tabellen und JSON um, dem Format der meisten Webdienste:"),
        code('local file = "~/Documents/LocalFlow test.json"\nfs.write(file, json.encode({ saved = time.today(), items = { "a", "b" } }))\nlocal data = json.decode(fs.read(file))\nlog("Gespeichert am " .. data.saved .. " mit " .. #data.items .. " Einträgen")\n'),
        t("**Das Web.** `http.get(adresse)` lädt eine Seite oder fragt einen Webdienst nach Daten, und `http.post(adresse, { json = ... })` sendet Daten, zum Beispiel an einen Discord-Webhook:"),
        code('local r = http.get("https://api.github.com/repos/lua/lua")\nif r.ok then\n    local repo = json.decode(r.body)\n    log(repo.full_name .. " hat " .. repo.stargazers_count .. " Sterne")\nend\n', false),
        t("**Große Suchen.** `fs.largest(ordner, 20)` findet die größten Dateien, und `security.scan(ordner)` markiert Dateinamen, die nach Schadsoftware aussehen. Um eine ganze Festplatte zu durchsuchen, fügen Sie sie (etwa `C:\\`) unter **Einstellungen › Erlaubte Ordner** hinzu und erhöhen Sie **Einstellungen › Zeitlimit für Skripte** auf einige Minuten."),
        warning("`security.scan` prüft nur Datei*namen*. Es ist kein Virenscanner: Echte Schadsoftware kann beliebig heißen, und ein Treffer kann harmlos sein. Prüfen Sie Funde mit Ihrem Virenscanner."),
        t("**Teilen.** Klicken Sie bei einer Automatisierung auf **Exportieren**, um sie als `.localflow`-Datei zu speichern, und schicken Sie die Datei einem Freund. Er öffnet sie über **📥 Importieren** in der Seitenleiste, per Doppelklick oder indem er sie auf das LocalFlow-Fenster zieht."),
        tip("Importierte Automatisierungen kommen **ausgeschaltet** an, mit einer Liste dessen, was sie tun können (Dateien löschen, Apps öffnen, das Internet nutzen …). Lesen Sie den Code und machen Sie einen Testlauf, bevor Sie eine einschalten, und importieren Sie nur von Personen, denen Sie vertrauen."),
      ],
    },
  ],

  hints: {
    fieldCall: (m, fs) => `Dort gibt es keine Funktion namens \`${m[1]}\`. Prüfen Sie die Schreibweise. Verfügbar: ${fs}.`,
    blockedGlobal: (m) => `\`${m[1]}\` ist in LocalFlow aus Sicherheitsgründen nicht verfügbar. Verwenden Sie für Dateien die \`fs.*\`-Funktionen.`,
    globalCall: (m) => `\`${m[1]}\` ist keine bekannte Funktion. Prüfen Sie die Schreibweise (Groß-/Kleinschreibung zählt) oder definieren Sie sie mit \`local function ${m[1]}() ... end\` *oberhalb* der Zeile, die sie verwendet.`,
    nilValue: (m) => `\`${m[1]}\` hat hier keinen Wert. Vielleicht ein Tippfehler, oder die Variable wurde nie mit \`local ${m[1]} = ...\` gesetzt.`,
    concatNil: (m) => `Sie verbinden Text mit \`..\`, aber ${m[1] ? `\`${m[1]}\`` : "einer der Werte"} ist \`nil\` (leer). Sorgen Sie für einen Wert oder verwenden Sie \`tostring(...)\`.`,
    concatType: (m) => `Eine ${m[1] === "table" ? "Tabelle" : "Wahrheitswert-Variable"} lässt sich nicht direkt mit \`..\` verbinden. Verpacken Sie sie: \`tostring(wert)\`${m[1] === "table" ? " oder verwenden Sie `#liste` für die Anzahl" : ""}.`,
    arith: () => "Sie rechnen oder vergleichen mit etwas, das keine Zahl ist (oder `nil`). Protokollieren Sie die Werte, um sie zu prüfen.",
    missingEnd: () => "Ein `end` fehlt. Jedes `if`, `for`, `while` und `function` braucht sein eigenes `end`.",
    missingThen: () => "`if` braucht nach der Bedingung ein `then`: `if x > 1 then ... end`. Zum Vergleichen `==` verwenden, nicht `=`.",
    missingDo: () => "Schleifen brauchen `do`: `for _, file in ipairs(files) do ... end`.",
    missingEquals: () => "Lua hat das als Zuweisung gelesen. Prüfen Sie auf ein falsch geschriebenes Schlüsselwort oder eine fehlende `(` bei einem Funktionsaufruf.",
    unfinishedString: () => "Einem Text fehlt das schließende Anführungszeichen `\"`.",
    missingBrace: () => "Einer `{` fehlt die schließende `}`. Prüfen Sie auch die Kommas zwischen Einträgen, etwa `name = \"x\",`.",
    missingParen: () => "Einer `(` fehlt die schließende `)`. Prüfen Sie auch, ob beim Verbinden von Text ein `..` fehlt.",
    unexpectedSymbol: () => "Lua hat diese Zeile nicht verstanden. Suchen Sie nach fehlenden Anführungszeichen, `..` zwischen Texten, Kommas oder `then`/`do`.",
    accessDenied: () => "Skripte dürfen nur Dateien in Ihren erlaubten Ordnern verwenden. Prüfen Sie den Pfad oder fügen Sie den Ordner in den Einstellungen hinzu.",
    notFound: () => "Diesen Pfad gibt es nicht. Denken Sie daran: `~` ist Ihr Benutzerordner. Prüfen Sie vorher mit `fs.exists(pfad)`.",
    destExists: () => "`fs.move` überschreibt nie. Prüfen Sie vorher mit `fs.exists(target)` und überspringen oder benennen Sie um.",
    timedOut: () => "Das Skript lief zu lange, meist wegen einer Schleife, die nie endet. Prüfen Sie Ihre `while`-Schleifen. Für große Suchen erhöhen Sie **Einstellungen › Zeitlimit für Skripte**.",
    missingRun: () => "Fügen Sie `run = function(ctx) ... end` in `automation { ... }` ein.",
    appNotFound: () => "Verwenden Sie den Namen aus dem Startmenü, etwa `\"Spotify\"`. Führen Sie `app.shortcuts()` (oder die Vorlage *Meine Apps anzeigen*) aus, um alle Namen zu sehen, oder geben Sie den vollständigen Pfad zur .exe an.",
    timeLimit: () => "Skripte müssen innerhalb ihres Zeitlimits fertig sein, inklusive `wait(...)`. Verwenden Sie kürzere Wartezeiten oder erhöhen Sie **Einstellungen › Zeitlimit für Skripte**.",
    badArgument: () => "Eine Funktion hat einen falschen Werttyp bekommen, oft fehlt ein Argument oder es steht eine Zahl, wo Text erwartet wird.",
  },
};
