// Deutsche Übersetzung der Anleitung. Der Lua-Code bleibt gleich, übersetzt sind Kommentare und Meldungen.

import { code, t, tip, warning, type GuideTranslation } from "./blocks";

export const de: GuideTranslation = {
  api: {
    "fs.list": { summary: "Listet die Dateien in einem Ordner auf, deren Namen zum `Muster` passen. `*` steht für beliebig viele Zeichen, `?` für genau eines. Groß- und Kleinschreibung spielt keine Rolle.", returns: "eine Liste vollständiger Dateipfade" },
    "fs.move": { summary: "Verschiebt oder benennt eine Datei um. Ist das `Ziel` ein vorhandener Ordner, behält die Datei ihren Namen. Fehlende Ordner werden angelegt. Überschreibt nie eine vorhandene Datei.", returns: "den neuen Pfad" },
    "fs.copy": { summary: "Kopiert eine Datei. Funktioniert wie `fs.move`, behält aber das Original. Gibt es die Kopie schon, kommt die alte zuerst in den Windows-Papierkorb.", returns: "den Pfad der Kopie" },
    "fs.exists": { summary: "Prüft, ob eine Datei oder ein Ordner existiert.", returns: "`true` oder `false`" },
    "fs.delete": { summary: "Verschiebt eine Datei oder einen Ordner in den Windows-Papierkorb, von wo sie jederzeit wiederhergestellt werden können.", returns: "`true`, wenn etwas gelöscht wurde, `false`, wenn es nicht existierte" },
    "fs.mkdir": { summary: "Legt einen Ordner an, samt fehlender übergeordneter Ordner. Tut nichts, wenn er schon existiert.", returns: "den Pfad des Ordners" },
    "fs.basename": { summary: "Der Dateiname am Ende eines Pfads.", returns: "Text, z. B. `report.pdf`" },
    "fs.join": { summary: "Setzt Ordner- und Dateinamen zu einem Pfad zusammen und fügt die Trennzeichen selbst ein.", returns: "den zusammengesetzten Pfad" },
    "fs.is_dir": { summary: "Prüft, ob ein Pfad ein Ordner ist (und keine Datei).", returns: "`true` oder `false`" },
    "fs.size": { summary: "Die Größe einer Datei in Bytes. Teilen Sie durch `1024 * 1024` für Megabytes.", returns: "eine Anzahl Bytes" },
    "fs.modified": { summary: "Wann eine Datei zuletzt geändert wurde, als Zeitstempel. Vergleichen Sie mit `time.now()`, um alte Dateien zu finden.", returns: "einen Zeitstempel (Sekunden seit 1970)" },
    "app.open": { summary: "Öffnet eine App über ihren Namen im Startmenü (z. B. `\"Spotify\"`), eine Datei oder einen Ordner mit dem passenden Programm, eine Website oder ein Programm über seinen Pfad. `args` ist eine optionale Liste mit Optionen für ein Programm.", returns: "was geöffnet wurde" },
    "app.close": { summary: "Schließt alle Fenster einer App höflich, wie ein Klick auf ✕, damit sie noch zum Speichern auffordern kann. Braucht **Systemsteuerung erlauben**. Um ein Programm sofort zu beenden, nutze `process.kill`.", returns: "wie viele Fenster geschlossen wurden" },
    "app.running": { summary: "Prüft, ob ein Programm läuft. Verwenden Sie den Programmnamen, z. B. `\"Discord\"` oder `\"chrome\"`; Groß-/Kleinschreibung und `.exe` sind egal.", returns: "`true` oder `false`" },
    "app.list": { summary: "Die Namen aller gerade laufenden Programme. Praktisch, um den Namen für `app.running` herauszufinden.", returns: "eine Liste von Namen" },
    "app.shortcuts": { summary: "Die Namen der Apps im Startmenü, also genau die Namen, die `app.open` versteht.", returns: "eine Liste von Namen" },
    "wait": { summary: "Pausiert das Skript. Nützlich zwischen dem Öffnen von Apps. Das ganze Skript muss trotzdem innerhalb seines Zeitlimits (30 Sekunden) fertig werden." },
    "time.now": { summary: "Die aktuelle Zeit als Zeitstempel: eine Anzahl Sekunden, mit der man leicht rechnen kann.", returns: "einen Zeitstempel" },
    "time.format": { summary: "Wandelt einen Zeitstempel in Text um. Beide Angaben sind optional: Standard ist das Muster `%Y-%m-%d %H:%M:%S` und die aktuelle Zeit. `%Y` Jahr, `%m` Monat, `%d` Tag, `%H` Stunde, `%M` Minute, `%A` Wochentag.", returns: "Text, z. B. `2026-09-29 14:05:00`" },
    "time.date": { summary: "Zerlegt eine Zeit in Teile: `year`, `month`, `day`, `hour`, `min`, `sec`, `weekday` (1 = Montag … 7 = Sonntag) und `yday` (Tag im Jahr). Ohne Zeitstempel: jetzt.", returns: "eine Tabelle" },
    "time.today": { summary: "Das heutige Datum als Text, ideal für Ordnernamen.", returns: "Text wie `2026-09-29`" },
    "time.days": { summary: "Rechnet Tage, Stunden oder Minuten in Sekunden um, damit Sie sie mit Zeitstempeln vergleichen können.", returns: "eine Anzahl Sekunden" },
    "fs.read": { summary: "Liest eine ganze Textdatei (bis 10 MB).", returns: "den Text der Datei" },
    "fs.write": { summary: "Erstellt eine Textdatei oder ersetzt ihren Inhalt (die alte Datei kommt in den Windows-Papierkorb). Fehlende Ordner werden angelegt.", returns: "den Pfad der Datei" },
    "fs.append": { summary: "Hängt Text an das Ende einer Datei an (und legt sie bei Bedarf an). Praktisch für eigene Protokolldateien.", returns: "den Pfad der Datei" },
    "fs.rename": { summary: "Benennt eine Datei oder einen Ordner am selben Ort um. `new_name` ist nur ein Name, ohne Ordner. Überschreibt nie.", returns: "den neuen Pfad" },
    "fs.list_dirs": { summary: "Die Ordner direkt in einem Ordner.", returns: "eine Liste von Ordnerpfaden" },
    "fs.find": { summary: "Wie `fs.list`, sucht aber auch in allen Unterordnern. Stoppt beim Zeitlimit des Skripts; das zweite Ergebnis ist dann `false`.", returns: "eine Liste von Dateipfaden und ob die Suche fertig wurde" },
    "fs.largest": { summary: "Die größten Dateien in einem Ordner und allen Unterordnern, die größte zuerst. `count` ist standardmäßig 10. Um eine ganze Festplatte zu durchsuchen, fügen Sie sie (etwa `C:\\`) in den Einstellungen zu den erlaubten Ordnern hinzu und erhöhen Sie das Zeitlimit.", returns: "eine Liste von `{ path = ..., size = ... }` und ob die Suche fertig wurde" },
    "fs.hash": { summary: "Der SHA-256-Fingerabdruck einer Datei. Dateien mit gleichem Fingerabdruck haben denselben Inhalt. Sie können ihn auch bei einem Dienst wie VirusTotal einfügen, um eine Datei zu prüfen.", returns: "64 Hexadezimalzeichen" },
    "zip.create": { summary: "Packt eine Datei, einen Ordner oder eine Liste davon in ein ZIP-Archiv.", returns: "wie viele Dateien hinzugefügt wurden" },
    "zip.extract": { summary: "Entpackt ein ZIP-Archiv in einen Ordner. Ersetzte Dateien kommen in den Windows-Papierkorb, und Archive, die außerhalb dieses Ordners schreiben wollen, werden abgelehnt.", returns: "wie viele Dateien entpackt wurden" },
    "security.scan": { summary: "Sucht nach Dateinamen, die für Schadsoftware typisch sind: Wörter wie `trojan`, `rootkit`, `worm` oder `keylogger`, gefälschte doppelte Endungen wie `invoice.pdf.exe` und Namen von Windows-Systemprogrammen außerhalb des Windows-Ordners. Es werden nur Namen geprüft; das ist kein Virenscanner.", returns: "eine Liste von `{ path = ..., reason = ... }` und ob die Prüfung fertig wurde" },
    "system.disks": { summary: "Ihre Festplatten mit Größe und freiem Speicher in Bytes.", returns: "eine Liste von `{ name, mount, total, free, removable }`" },
    "system.disk_free": { summary: "Freier Speicher in Bytes auf der Festplatte, auf der `path` liegt (ohne Angabe: Ihr Benutzerordner).", returns: "eine Anzahl Bytes" },
    "system.memory": { summary: "Arbeitsspeicher (RAM) in Bytes.", returns: "`{ total, used, free }`" },
    "system.cpu": { summary: "Wie ausgelastet der Prozessor gerade ist, von 0 bis 100. Die Messung dauert einen Sekundenbruchteil.", returns: "einen Prozentwert" },
    "system.battery": { summary: "Der Akkustand eines Laptops. `nil` auf einem PC ohne Akku.", returns: "`{ percent, charging, plugged_in }` oder `nil`" },
    "system.uptime": { summary: "Wie lange der Computer schon läuft, in Sekunden.", returns: "eine Anzahl Sekunden" },
    "system.computer_name": { summary: "Der Name dieses Computers.", returns: "Text" },
    "system.user_name": { summary: "Der Name des Windows-Benutzers.", returns: "Text" },
    "system.os": { summary: "Die Windows-Version.", returns: "Text, z. B. `Windows 11 (26100)`" },
    "clipboard.get": { summary: "Der Text, der gerade in der Zwischenablage ist (was Sie kopiert haben). `nil`, wenn es kein Text ist.", returns: "Text oder `nil`" },
    "clipboard.set": { summary: "Legt Text in die Zwischenablage, bereit zum Einfügen." },
    "ask": { summary: "Zeigt ein Ja/Nein-Fenster und wartet auf Ihre Antwort. Nützlich vor größeren Aktionen. Die Wartezeit zählt zum Zeitlimit.", returns: "`true` für Ja, `false` für Nein" },
    "sound.beep": { summary: "Spielt den Standard-Windows-Ton." },
    "sound.play": { summary: "Spielt eine .wav-Datei im Hintergrund ab." },
    "json.encode": { summary: "Wandelt eine Lua-Tabelle in JSON-Text um, das Format der meisten Webdienste. Mit `true` als `pretty` wird es gut lesbar.", returns: "Text" },
    "json.decode": { summary: "Wandelt JSON-Text in eine Lua-Tabelle um.", returns: "einen Lua-Wert" },
    "http.get": { summary: "Lädt eine Webseite oder fragt einen Webdienst nach Daten. Fehlerseiten stoppen das Skript nicht: Prüfen Sie `ok` oder `status`.", returns: "`{ status, ok, body }`" },
    "http.post": { summary: "Sendet Daten an einen Webdienst, als JSON (`json = tabelle`) oder als Text (`body = \"...\"`). Praktisch für Discord- oder Telegram-Webhooks.", returns: "`{ status, ok, body }`" },
    "store.get": { summary: "Liest einen Wert, den diese Automatisierung in einem früheren Lauf gespeichert hat. Gibt `default` zurück, wenn es keinen gibt. Testläufe beginnen immer mit leerem Speicher.", returns: "den gespeicherten Wert" },
    "store.set": { summary: "Speichert Text, eine Zahl, `true`/`false` oder eine Tabelle, damit der nächste Lauf sie mit `store.get` lesen kann. Jede Automatisierung hat ihren eigenen Speicher." },
    "store.delete": { summary: "Vergisst einen gespeicherten Wert." },
    "shell.run": { summary: "🔒 Braucht **Systemsteuerung**. Führt einen Befehl wie in der Eingabeaufforderung aus und wartet darauf. Die Ausgabe wird erfasst; es blitzt kein Fenster auf. Stoppt den Befehl nach `timeout` Sekunden (Standard 60).", returns: "`{ code, ok, output, error }`" },
    "shell.powershell": { summary: "🔒 Braucht **Systemsteuerung**. Wie `shell.run`, führt aber ein PowerShell-Skript aus.", returns: "`{ code, ok, output, error }`" },
    "process.list": { summary: "Alle laufenden Programme.", returns: "eine Liste von `{ pid, name, memory_mb }`" },
    "process.running": { summary: "Prüft, ob ein Programm läuft, wie `app.running`.", returns: "`true` oder `false`" },
    "process.wait_for": { summary: "Wartet, bis ein Programm läuft, höchstens `seconds` Sekunden (Standard 30).", returns: "`true`, wenn es rechtzeitig startete" },
    "process.kill": { summary: "🔒 Braucht **Systemsteuerung**. Beendet ein Programm sofort, ohne es speichern zu lassen. Für Apps mit offenen Dokumenten besser `window.close` verwenden. Windows-eigene Programme sind geschützt.", returns: "wie viele beendet wurden" },
    "window.list": { summary: "Alle sichtbaren Fenster, von vorne nach hinten.", returns: "eine Liste von `{ id, title, app, x, y, width, height, minimized, maximized }`" },
    "window.find": { summary: "Das erste Fenster, dessen App-Name `text` ist oder dessen Titel ihn enthält.", returns: "ein Fenster oder `nil`" },
    "window.active": { summary: "Das Fenster, in dem Sie gerade arbeiten.", returns: "ein Fenster oder `nil`" },
    "window.focus": { summary: "🔒 Braucht **Systemsteuerung**. Holt ein Fenster nach vorne. `window` ist ein Fenster aus `window.find` oder ein Suchtext." },
    "window.move": { summary: "🔒 Braucht **Systemsteuerung**. Verschiebt ein Fenster und ändert seine Größe, in Pixeln ab der linken oberen Bildschirmecke." },
    "window.minimize": { summary: "🔒 Braucht **Systemsteuerung**. Minimiert, maximiert oder stellt ein Fenster wieder her." },
    "window.close": { summary: "🔒 Braucht **Systemsteuerung**. Schließt ein Fenster höflich, wie ein Klick auf X: Die App kann noch nach dem Speichern fragen." },
    "keyboard.press": { summary: "🔒 Braucht **Systemsteuerung**. Drückt eine Tastenkombination wie `\"ctrl+c\"`, `\"alt+tab\"`, `\"win+d\"` oder `\"enter\"`. Medientasten: `volumeup`, `volumedown`, `mute`, `playpause`, `next`, `prev`." },
    "keyboard.type": { summary: "🔒 Braucht **Systemsteuerung**. Tippt Text in das vordere Fenster, als hätten Sie ihn eingegeben." },
    "mouse.click": { summary: "🔒 Braucht **Systemsteuerung**. Klickt an einer Position (oder dort, wo die Maus ist, wenn `x` und `y` fehlen). `button` ist `\"left\"`, `\"right\"` oder `\"middle\"`; `double = true` doppelklickt." },
    "mouse.move": { summary: "🔒 Braucht **Systemsteuerung**. Bewegt den Mauszeiger." },
    "mouse.position": { summary: "Wo der Mauszeiger ist. Praktisch, um Koordinaten für `mouse.click` zu finden.", returns: "`x, y`" },
    "screen.size": { summary: "Die Größe des Hauptbildschirms in Pixeln.", returns: "`width, height`" },
    "system.lock": { summary: "🔒 Braucht **Systemsteuerung**. Sperrt den PC, wie Win+L." },
    "system.sleep": { summary: "🔒 Braucht **Systemsteuerung**. Versetzt den PC in den Energiesparmodus." },
    "system.shutdown": { summary: "🔒 Braucht **Systemsteuerung**. Fährt den PC nach `delay` Sekunden herunter oder startet ihn neu (Standard 60). Windows zeigt eine Warnung, und `system.cancel_shutdown()` (oder `shutdown /a`) bricht ab.", returns: "die Verzögerung" },
    "system.cancel_shutdown": { summary: "🔒 Braucht **Systemsteuerung**. Bricht ein geplantes Herunterfahren oder einen Neustart ab.", returns: "`true`, wenn etwas abgebrochen wurde" },
    "system.volume_up": { summary: "🔒 Braucht **Systemsteuerung**. Ändert die Lautstärke wie die Lautstärketasten (ein Schritt meist 2 %). `mute` schaltet den Ton aus oder wieder ein." },
    "system.brightness": { summary: "🔒 Braucht **Systemsteuerung**. Stellt die Bildschirmhelligkeit ein. Funktioniert bei Laptop-Bildschirmen; die meisten externen Monitore unterstützen es nicht." },
    "system.set_wallpaper": { summary: "🔒 Braucht **Systemsteuerung**. Setzt den Desktop-Hintergrund." },
    "system.wake_at": { summary: "🔒 Braucht **Systemsteuerung**. Weckt den PC zu einer Uhrzeit aus dem **Ruhezustand**: `\"07:30\"` (nächstes 7:30) oder `\"2026-10-01 07:30\"`. Einen ausgeschalteten PC kann es nicht einschalten. Windows muss Zeitgeber zur Aktivierung erlauben (Energieoptionen › Energie sparen › Zeitgeber zur Aktivierung zulassen).", returns: "die Weckzeit als Text" },
    "system.cancel_wake": { summary: "🔒 Braucht **Systemsteuerung**. Entfernt den mit `system.wake_at` gesetzten Weck-Timer." },
    "system.idle_seconds": { summary: "Wie lange niemand Tastatur oder Maus benutzt hat.", returns: "Sekunden" },
    "network.wake_on_lan": { summary: "Weckt einen anderen PC im Netzwerk, bei dem Wake-on-LAN eingeschaltet ist. `mac` ist die Adresse seiner Netzwerkkarte.", returns: "`true`, wenn das Signal gesendet wurde" },
    "ctx.app": { summary: "Für App-Auslöser: das Programm, das gestartet oder geschlossen wurde." },
    "ctx.drive": { summary: "Für den USB-Auslöser: das angeschlossene Laufwerk, etwa `E:\\`. Der Lauf darf dieses Laufwerk verwenden." },
    "log": { summary: "Schreibt eine Zeile in das Protokoll dieser Automatisierung und in die Ausgabe. So sehen Sie, was Ihr Skript tut." },
    "notify": { summary: "Zeigt eine Windows-Benachrichtigung (wenn in den Einstellungen aktiviert) und schreibt sie ins Protokoll." },
    "print": { summary: "Wie `log`, nimmt aber mehrere Werte und setzt einen Tabulator dazwischen." },
    "ctx.name": { summary: "Der Name der laufenden Automatisierung. Verfügbar in `run = function(ctx)`." },
    "ctx.trigger": { summary: 'Wie der Lauf gestartet wurde: `"manual"` (Jetzt ausführen), `"tray"` (Menü im Infobereich), `"schedule"`, `"startup"`, `"watch"` (neue Datei) oder `"test"` (Testlauf).' },
    "ctx.file": { summary: "Für Automatisierungen, die einen Ordner überwachen: der vollständige Pfad der gerade erschienenen Datei. Sonst `nil`." },
    "require": { summary: "Lädt eine der eingebauten Hilfsbibliotheken von LocalFlow: `lf.strings`, `lf.tables`, `lf.paths`, `lf.dates`, `lf.retry`, `lf.template`, `lf.report` und `lf.test`. Siehe die Lektion *Fertige Helfer*.", returns: "die Bibliothek als Tabelle von Funktionen" },
    "fs.duplicates": { summary: "Findet Dateien mit genau gleichem Inhalt in einem Ordner und seinen Unterordnern, die größten zuerst. `pattern` (optional) beschränkt auf Namen wie `\"*.jpg\"`. Leere Dateien werden übersprungen.", returns: "eine Liste von Gruppen `{ size, hash, files }` und ob die Suche fertig wurde" },
    "image.info": { summary: "Liest Größe und Format eines Bildes (PNG, JPG, WebP, GIF oder BMP), ohne es ganz zu laden.", returns: "eine Tabelle mit `width`, `height` und `format`" },
    "image.resize": { summary: "Speichert eine kleinere Kopie eines Bildes, die in `max_width` × `max_height` passt (Höhe standardmäßig wie die Breite). Das Seitenverhältnis bleibt, kleine Bilder werden nie vergrößert. Die Endung der neuen Datei bestimmt das Format.", returns: "der Pfad des neuen Bildes" },
    "image.convert": { summary: "Speichert ein Bild in einem anderen Format, festgelegt durch die neue Endung: `.png`, `.jpg`, `.webp`, `.gif` oder `.bmp`.", returns: "der Pfad des neuen Bildes" },
    "image.taken": { summary: "Wann ein Foto aufgenommen wurde, laut dem Datum, das die Kamera darin gespeichert hat (EXIF). Screenshots und bearbeitete Bilder haben oft keins.", returns: "ein Zeitstempel oder `nil`" },
    "csv.read": { summary: "Liest eine CSV-Datei (Excel kann solche speichern). Mit Kopfzeile (Standard) ist jede Zeile eine Tabelle nach Spaltennamen; `{ header = false }` liefert einfache Listen. `separator` kann `\";\"` oder `\"tab\"` sein.", returns: "eine Liste von Zeilen" },
    "csv.write": { summary: "Speichert Zeilen als CSV-Datei. Zeilen sind Listen oder, mit `{ header = { ... } }`, Tabellen nach Spaltennamen. Eine ältere Datei mit dem Namen kommt in den Papierkorb.", returns: "der Pfad der Datei" },
    "crypto.encrypt": { summary: "Speichert eine gesperrte Kopie einer Datei, die sich nur mit dem Passwort öffnet (XChaCha20-Poly1305 mit Argon2-Schlüssel). Das Passwort braucht 8+ Zeichen. **Wer es vergisst, kann die Datei nie mehr öffnen.**", returns: "der Pfad der gesperrten Datei" },
    "crypto.decrypt": { summary: "Öffnet eine mit `crypto.encrypt` gesperrte Datei und speichert den ursprünglichen Inhalt. Ein falsches Passwort ergibt einen Fehler, und nichts wird geschrieben.", returns: "der Pfad der geöffneten Datei" },
    "crypto.password": { summary: "Erzeugt ein zufälliges Passwort (16 Zeichen, wenn nicht anders angegeben), ohne verwechselbare Zeichen wie `0` und `O`.", returns: "das Passwort" },
    "metrics.average": { summary: "Der Durchschnitt von `\"cpu\"`, `\"memory\"`, `\"disk\"` oder `\"battery\"` (in %) über die letzten `minutes` Minuten (Standard 60), aus dem Verlauf, den LocalFlow jede Minute aufzeichnet. `metrics.peak` und `metrics.lowest` funktionieren genauso.", returns: "ein Prozentwert oder `nil`, wenn es noch keinen Verlauf gibt" },
    "metrics.recent": { summary: "Die aufgezeichneten Werte der letzten `minutes` Minuten, älteste zuerst. `metrics.latest()` liefert nur den neuesten.", returns: "eine Liste von `{ at, cpu, memory, disk, battery }`" },
    "time.parse": { summary: "Macht aus einem als Text geschriebenen Datum einen Zeitstempel. Versteht `\"2026-09-29\"` und `\"2026-09-29 14:05\"`; für andere Formen gib ein `format` wie `\"%d.%m.%Y\"` an.", returns: "ein Zeitstempel oder `nil`, wenn der Text kein Datum ist" },
    "time.make": { summary: "Baut einen Zeitstempel aus Teilen. Werte laufen wie im Kalender über, `day = 32` im Januar ist also der 1. Februar.", returns: "ein Zeitstempel" },
    "ai.ask": { summary: "Fragt die KI (GigaChat) und wartet auf die Antwort. Braucht einen Schlüssel unter **Einstellungen › KI**. `options` kann `system` (wie geantwortet werden soll), `model`, `temperature` (0 = genau, 1 = kreativ) `max_tokens` und `cache_hours = 24` enthalten, um die Antwort auf genau dieselbe Frage wiederzuverwenden. Der Text geht an Sbers Server.", returns: "die Antwort als Text" },
    "ai.chat": { summary: "Ein ganzes Gespräch: eine Liste von `{ role = \"user\" | \"assistant\" | \"system\", content = \"...\" }`. Nützlich, wenn die KI frühere Fragen und Antworten kennen soll.", returns: "die nächste Antwort als Text" },
    "ai.conversation": { summary: "Ein Chat, der frühere Fragen und Antworten zwischen Läufen dieser Automatisierung behält (die letzten 20 Nachrichten oder `keep = n`). Nutze `chat:ask(text)`, `chat:history()` und `chat:forget()`. Testläufe beginnen mit leerem Gedächtnis.", returns: "ein Chat-Objekt" },
    "ai.available": { summary: "`true`, wenn in den Einstellungen ein GigaChat-Schlüssel gespeichert ist, damit ein Skript den KI-Teil überspringen kann.", returns: "`true` oder `false`" },
    "desktop.set_dark_mode": { summary: "Liest oder wechselt den dunklen und hellen Modus von Windows (Apps und Taskleiste). Ändern braucht **Systemsteuerung erlauben**.", returns: "`true`, wenn dunkel" },
    "desktop.set_transparency": { summary: "Liest oder schaltet die Transparenzeffekte von Windows. Ändern braucht **Systemsteuerung erlauben**.", returns: "`true` oder `false`" },
    "desktop.set_accent_color": { summary: "Liest oder setzt die Akzentfarbe von Windows als `#rrggbb`. Ändern braucht **Systemsteuerung erlauben**.", returns: "eine Farbe wie `\"#0078d4\"`" },
    "desktop.set_wallpaper": { summary: "Liest das aktuelle Hintergrundbild oder setzt ein Bild mit Stil: `\"fill\"` (Standard), `\"fit\"`, `\"stretch\"`, `\"center\"`, `\"tile\"` oder `\"span\"`. Ändern braucht **Systemsteuerung erlauben**.", returns: "der Pfad des Hintergrundbilds" },
    "system.set_volume": { summary: "Liest oder setzt die genaue Lautstärke von 0 bis 100. `system.muted()` und `system.set_mute(true)` tun dasselbe für Stummschalten. Ändern braucht **Systemsteuerung erlauben**.", returns: "die Lautstärke in %" },
    "power.set_plan": { summary: "Listet Energiesparpläne, zeigt den aktiven oder wechselt: `\"balanced\"`, `\"high performance\"`, `\"power saver\"` (gleich in jeder Windows-Sprache). `power.set_screen_off(Minuten)` und `power.set_sleep(Minuten)` setzen die Zeiten (0 = nie; `\"plugged\"` oder `\"battery\"` für nur einen Fall). Ändern braucht **Systemsteuerung erlauben**.", returns: "der Name des Plans" },
    "mouse.set_speed": { summary: "Liest oder setzt die Zeigergeschwindigkeit von 1 (langsam) bis 20 (schnell); Windows-Standard ist 10. Ändern braucht **Systemsteuerung erlauben**.", returns: "die Geschwindigkeit" },
    "explorer.set_hidden_files": { summary: "Ob der Explorer versteckte Dateien zeigt. `explorer.file_extensions()` und `explorer.set_file_extensions(true)` tun dasselbe für Endungen wie `.pdf`. Ändern braucht **Systemsteuerung erlauben**.", returns: "`true`, wenn angezeigt" },
    "ctx.input": { summary: "Daten von der Automatisierung, die diese gestartet hat: was an `automations.call` übergeben wurde, oder was die vorherige Automatisierung beim Auslöser **Nach … ausführen** zurückgegeben hat. Sonst `nil`." },
    "automations.call": { summary: "Führt eine andere gespeicherte Automatisierung als Schritt aus und wartet darauf. `input` (optional) kommt dort als `ctx.input` an. Stoppt dieses Skript, wenn der Schritt fehlschlägt. Groß- und Kleinschreibung im Namen ist egal.", returns: "was `run` des Schritts zurückgegeben hat" },
    "automations.run": { summary: "Wie `automations.call`, stoppt dieses Skript aber nie. Prüfe `ok`, um zu sehen, ob der Schritt geklappt hat.", returns: "eine Tabelle mit `ok`, `error` und `result`" },
    "automations.list": { summary: "Alle gespeicherten Automatisierungen, auch ausgeschaltete, die trotzdem als Schritte funktionieren.", returns: "eine Liste von Tabellen mit `id`, `name` und `enabled`" },
    "ctx.id": { summary: "Die Nummer der Automatisierung. `0` bei Testläufen." },
  },

  snippets: {
    "Remember between runs": { title: "Zwischen Läufen merken", description: "Läufe zählen oder den letzten Wert mit store behalten." },
    "Ask before doing it": { title: "Vorher fragen", description: "Zuerst eine Ja/Nein-Frage zeigen." },
    "Largest files": { title: "Größte Dateien", description: "Die größten Dateien in einem Ordner auflisten." },
    "Send a webhook message": { title: "Webhook-Nachricht senden", description: "Eine Nachricht an Discord (oder einen anderen Webhook) schicken." },
    "Warn on low battery": { title: "Bei schwachem Akku warnen", description: "Benachrichtigen, wenn der Laptop-Akku fast leer ist." },
    "Run a command": { title: "Befehl ausführen", description: "Einen Befehl ausführen und die Ausgabe protokollieren (braucht Systemsteuerung)." },
    "Bring a window to the front": { title: "Fenster nach vorne holen", description: "Ein Fenster per App oder Titel finden und aktivieren (braucht Systemsteuerung)." },
    "Only when I'm away": { title: "Nur wenn ich weg bin", description: "Früh aufhören, wenn Tastatur oder Maus in den letzten 5 Minuten benutzt wurden." },
    "Open apps if not running": { title: "Apps öffnen, falls nicht offen", description: "Öffnet eine Liste von Apps und überspringt bereits offene." },
    "Handle the new file": { title: "Neue Datei verarbeiten", description: "Für Automatisierungen, die einen Ordner überwachen: ctx.file verwenden." },
    "Files older than N days": { title: "Dateien älter als N Tage", description: "Findet Dateien, die sich länger nicht geändert haben." },
    "Folder for today": { title: "Ordner für heute", description: "Legt einen Ordner mit dem heutigen Datum an." },
    "Only on weekdays": { title: "Nur werktags", description: "Hört am Samstag und Sonntag gleich auf." },
    "Loop over files": { title: "Dateien durchgehen", description: "Mit jeder passenden Datei etwas tun." },
    "Move without overwriting": { title: "Verschieben ohne Überschreiben", description: "Verschiebt eine Datei nur, wenn das Ziel noch nicht existiert." },
    "Count and notify": { title: "Zählen und melden", description: "Zählt mit und meldet das Ergebnis am Ende." },
    "Name contains a word": { title: "Name enthält ein Wort", description: "Prüft, ob ein Dateiname einen bestimmten Text enthält." },
    "Get the file extension": { title: "Dateiendung ermitteln", description: "Macht aus „photo.JPG“ ein „jpg“." },
    "Sort files by type": { title: "Dateien nach Typ sortieren", description: "Verschiebt Dateien in Ordner, die nach ihrer Endung benannt sind." },
    "Dry run in tests": { title: "Probelauf im Test", description: "Beim Testlauf nur protokollieren, was passieren würde." },
    "Run another automation": { title: "Andere Automatisierung ausführen", description: "Eine gespeicherte Automatisierung als Schritt nutzen und ihr Daten übergeben." },
    "Readable file sizes": { title: "Lesbare Dateigrößen", description: "Zeigt Größen wie \"1.5 MB\" mit lf.paths." },
    "Warn at most every few hours": { title: "Höchstens alle paar Stunden warnen", description: "Dieselbe Warnung nur ab und zu senden." },
    "Fill in a text template": { title: "Textvorlage ausfüllen", description: "Werte in {Platzhalter} einsetzen." },
    "Stop early": { title: "Früh aufhören", description: "Verlässt run, wenn es nichts zu tun gibt." },
  },

  lessons: [
    {
      id: "first",
      title: "1. Ihre erste Automatisierung",
      summary: "Wie eine Automatisierung aussieht und wie man sie ausprobiert.",
      blocks: [
        t("Eine Automatisierung ist ein kleines Programm in Lua, einer einfachen Skriptsprache, die in Spielen und Programmen verwendet wird. Jede Automatisierung hat dieselbe Form:"),
        code('automation {\n    name = "Hallo sagen",\n\n    run = function(ctx)\n        log("Hallo, Welt!")\n    end\n}\n'),
        t("`automation { ... }` beschreibt Ihre Automatisierung. `name` ist ihr Name, und `run` ist der Code, der bei jedem Start ausgeführt wird. Alles zwischen `function(ctx)` und dem passenden `end` ist Ihr Programm."),
        t("`log(...)` schreibt eine Zeile in die Ausgabe, damit Sie sehen, was Ihr Skript tut."),
        tip("Klicken Sie bei einem Beispiel auf dieser Seite auf **Im Editor öffnen** und dann auf **Testlauf** (Strg+Enter). Die Ausgabe erscheint unter dem Editor. Gespeichert wird erst, wenn Sie auf „Speichern“ klicken."),
        t("Zeilen, die mit `--` beginnen, sind Kommentare. Lua ignoriert sie, sie sind Notizen für Menschen:"),
        code('-- Diese ganze Zeile ist ein Kommentar\nlog("Das wird ausgeführt") -- dieser Teil ist auch ein Kommentar\n'),
      ],
    },
    {
      id: "values",
      title: "2. Werte und Variablen",
      summary: "Text, Zahlen und wie man ihnen Namen gibt.",
      blocks: [
        t("Eine Variable ist ein Name für einen Wert. Sie wird mit `local` angelegt:"),
        code('local folder = "~/Downloads"\nlocal limit = 10\nlocal enabled = true\n\nlog(folder)\nlog(limit)\n'),
        t("Text (eine sogenannte *Zeichenkette*) steht in doppelten Anführungszeichen, Zahlen nicht. `true` und `false` sind Ja/Nein-Werte. `nil` bedeutet „kein Wert“."),
        t("Text verbinden Sie mit zwei Punkten, `..`:"),
        code('local name = "report"\nlocal file = name .. ".pdf"\nlog("Die Datei heißt " .. file)\n'),
        t("Zahlen funktionieren wie gewohnt: `+ - * /`. Um eine Variable zu ändern, weisen Sie ihr erneut etwas zu (ohne `local`):"),
        code('local count = 0\ncount = count + 1\ncount = count + 1\nlog("Zähler: " .. count)\n'),
        t("Text hat praktische Helfer. Sie werden mit einem Doppelpunkt nach dem Wert geschrieben:"),
        code('local name = "Holiday Photo.JPG"\nlog(name:lower())                 -- holiday photo.jpg\nlog(name:upper())                 -- HOLIDAY PHOTO.JPG\nlog(tostring(name:find("Photo")))  -- wo "Photo" beginnt: 9\nlog(name:sub(1, 7))               -- die ersten 7 Buchstaben: Holiday\n'),
        tip("`tostring(wert)` wandelt alles in Text um, praktisch vor dem Verbinden mit `..`. `lower` und `upper` ändern nur einfache lateinische Buchstaben (keine Umlaute)."),
      ],
    },
    {
      id: "decisions",
      title: "3. Entscheidungen treffen",
      summary: "Code nur ausführen, wenn etwas zutrifft.",
      blocks: [
        t("Mit `if ... then ... end` tun Sie etwas nur dann, wenn eine Bedingung zutrifft:"),
        code('local count = 12\n\nif count > 10 then\n    log("Das sind viele Dateien")\nelseif count > 0 then\n    log("Ein paar Dateien")\nelse\n    log("Keine Dateien")\nend\n'),
        t("Vergleiche: `==` gleich, `~=` ungleich, `<`, `>`, `<=`, `>=`. Kombinieren Sie sie mit `and`, `or` und `not`:"),
        code('local name = "invoice-march.pdf"\n\nif name:find("invoice") and not name:find("draft") then\n    log("Eine endgültige Rechnung")\nend\n'),
        warning("Ein `=` speichert einen Wert, zwei `==` vergleichen. `if count = 3 then` ist ein Fehler; schreiben Sie `if count == 3 then`."),
        t("Vor dem Bearbeiten einer Datei zu prüfen, ob sie existiert, ist eine sehr häufige Entscheidung:"),
        code('if fs.exists("~/Downloads") then\n    log("Der Downloads-Ordner ist da")\nelse\n    log("Kein Downloads-Ordner")\nend\n'),
      ],
    },
    {
      id: "loops",
      title: "4. Listen und Schleifen",
      summary: "Etwas für jede Datei wiederholen.",
      blocks: [
        t("Eine Liste enthält mehrere Werte in geschweiften Klammern. `#liste` sagt Ihnen, wie viele es sind:"),
        code('local fruits = { "Apfel", "Banane", "Kirsche" }\nlog("Ich habe " .. #fruits .. " Früchte")\nlog("Die erste ist " .. fruits[1])\n'),
        t("Um etwas mit jedem Eintrag zu tun, verwenden Sie die Schleife `for ... in ipairs(liste) do ... end`:"),
        code('local fruits = { "Apfel", "Banane", "Kirsche" }\n\nfor index, fruit in ipairs(fruits) do\n    log(index .. ": " .. fruit)\nend\n'),
        t("`fs.list` liefert eine Liste von Dateien, deshalb beginnt fast jede Datei-Automatisierung so. Schreiben Sie `_`, wenn Sie die Nummer nicht brauchen:"),
        code('local files = fs.list("~/Downloads", "*")\nlog("Downloads enthält " .. #files .. " Dateien")\n\nfor _, file in ipairs(files) do\n    log(fs.basename(file))\nend\n'),
        t("Zum Zählen gibt es die Zahlenschleife:"),
        code('for i = 1, 3 do\n    log("Runde " .. i)\nend\n'),
        tip("Auch Schleifen enden mit `end`. Jedes `if`, `for` und `function` braucht sein eigenes `end`."),
      ],
    },
    {
      id: "functions",
      title: "5. Eigene Funktionen",
      summary: "Einem Stück Code einen Namen geben und es wiederverwenden.",
      blocks: [
        t("Eine Funktion ist ein benanntes Stück Code, das Sie oft ausführen können. Definieren Sie sie, bevor Sie sie verwenden:"),
        code('local function greet(person)\n    log("Hallo, " .. person .. "!")\nend\n\ngreet("Anna")\ngreet("Ben")\n'),
        t("Funktionen können mit `return` einen Wert zurückgeben:"),
        code('local function extension(file)\n    return (file:match("%.([^.]+)$") or ""):lower()\nend\n\nlog(extension("photo.JPG"))   -- jpg\nlog(extension("notes.txt"))   -- txt\n'),
        t("`run = function(ctx) ... end` in Ihrer Automatisierung ist selbst eine Funktion. `return` darin beendet den Lauf vorzeitig."),
      ],
    },
    {
      id: "files",
      title: "6. Mit Dateien arbeiten",
      summary: "Pfade, Muster und sicheres Verschieben.",
      blocks: [
        t("Pfade zeigen auf Dateien und Ordner. `~` ist Ihr Benutzerordner, etwa `C:/Users/Sie`, also ist `~/Downloads` Ihr Downloads-Ordner. Auch unter Windows können Sie `/` schreiben."),
        t("`fs.list(ordner, muster)` findet Dateien. Im Muster steht `*` für „beliebig“:"),
        code('log(#fs.list("~/Downloads", "*.pdf") .. " PDFs")\nlog(#fs.list("~/Downloads", "*.zip") .. " ZIP-Dateien")\nlog(#fs.list("~/Downloads", "Screenshot*") .. " Screenshots")\n'),
        t("Ein sicheres Vorgehen beim Verschieben: Zielpfad zusammensetzen, bereits vorhandene Dateien überspringen und protokollieren, was passiert ist."),
        code('automation {\n    name = "PDFs ordnen",\n\n    run = function(ctx)\n        for _, file in ipairs(fs.list("~/Downloads", "*.pdf")) do\n            local target = fs.join("~/Documents/PDF", fs.basename(file))\n\n            if ctx.trigger == "test" then\n                log("Würde verschieben: " .. fs.basename(file))\n            elseif fs.exists(target) then\n                log("Übersprungen (schon vorhanden): " .. fs.basename(file))\n            else\n                fs.move(file, target)\n                log("Verschoben: " .. fs.basename(file))\n            end\n        end\n    end\n}\n'),
        warning("Testläufe ändern Dateien wirklich. Das Beispiel oben prüft `ctx.trigger == \"test\"`, damit ein Testlauf nur protokolliert, was er tun *würde*. Das ist eine gute Gewohnheit für jedes Skript, das verschiebt oder löscht."),
        tip("Skripte können nur Dateien in Ihren erlaubten Ordnern bearbeiten (Ihr Benutzerordner, sofern Sie es nicht in den Einstellungen geändert haben). Das schützt den Rest Ihres Computers."),
      ],
    },
    {
      id: "schedules",
      title: "7. Zeitpläne und Benachrichtigungen",
      summary: "Automatisch ausführen und darüber informiert werden.",
      blocks: [
        t("Wählen Sie über dem Editor einen **Zeitplan**, etwa *Jede Stunde* oder *Werktags um 9:00*, und speichern Sie. LocalFlow führt die Automatisierung dann selbst aus, solange sie aktiv ist und LocalFlow läuft. Wenn Sie das Fenster schließen, arbeitet es im Infobereich weiter (die Symbole neben der Uhr in der Taskleiste)."),
        t("Wenn die Vorgaben nicht passen, wählen Sie **Eigener…** und schreiben einen Cron-Ausdruck. Er hat sechs Teile: Sekunde, Minute, Stunde, Tag, Monat, Wochentag. `*` bedeutet „jede(r)“, `*/15` bedeutet „jede 15.“."),
        code("-- Beispiele (sie gehören in das Feld „Zeitplan“, nicht in den Code):\n--   0 */15 * * * *      alle 15 Minuten\n--   0 30 8 * * *        täglich um 8:30\n--   0 0 20 * * Sun      sonntags um 20:00\n--   0 0 9 1 * *         am 1. jedes Monats um 9:00\n", false),
        t("Mit `notify(...)` erhalten Sie eine Windows-Benachrichtigung. Das ist am Ende eines geplanten Laufs praktisch:"),
        code('local moved = 3 -- angenommen, wir haben 3 Dateien verschoben\nif moved > 0 then\n    notify(moved .. " Dateien verschoben")\nend\n'),
        tip("Schlägt ein geplanter Lauf fehl, zeigt LocalFlow ebenfalls eine Benachrichtigung. Benachrichtigungen schalten Sie in den Einstellungen ein oder aus."),
      ],
    },
    {
      id: "apps",
      title: "8. Apps öffnen",
      summary: "Programme und Websites mit einem Klick starten.",
      blocks: [
        t("`app.open(...)` startet Dinge für Sie. Übergeben Sie den Namen einer App aus dem Startmenü, eine Datei oder einen Ordner, eine Website oder den vollständigen Pfad zu einem Programm:"),
        code('app.open("notepad")\n'),
        code('app.open("Spotify")                        -- Name im Startmenü\napp.open("https://calendar.google.com")    -- Website\napp.open("~/Documents")                    -- Ordner\napp.open("C:/Program Files/App/app.exe")   -- Programm\n', false),
        t("Sie wissen nicht, wie eine App heißt? `app.shortcuts()` listet alle Namen aus Ihrem Startmenü auf:"),
        code('local names = app.shortcuts()\nlog(#names .. " Apps gefunden")\nfor i = 1, math.min(#names, 15) do\n    log(names[i])\nend\n'),
        t("Damit nichts doppelt geöffnet wird, prüfen Sie vorher mit `app.running(name)`. `wait(sekunden)` gibt einer App einen Moment zum Starten, bevor die nächste kommt:"),
        code('local apps = { "notepad" }\n\nfor _, name in ipairs(apps) do\n    if app.running(name) then\n        log(name .. " ist schon offen")\n    else\n        app.open(name)\n        log(name .. " geöffnet")\n        wait(1)\n    end\nend\n'),
        tip("**Alles bei der Anmeldung öffnen:** Aktivieren Sie über dem Editor **Beim Start von LocalFlow ausführen** und schalten Sie **Einstellungen › Mit Windows starten** ein. Oder klicken Sie mit der rechten Maustaste auf das LocalFlow-Symbol im Infobereich (neben der Uhr in der Taskleiste; klicken Sie auf ^, falls es nicht zu sehen ist) › **Ausführen**, um jede Automatisierung mit einem Klick zu starten."),
        t("Die Vorlage *Meine Arbeits-Apps öffnen* erledigt all das. Ändern Sie einfach die Liste der Namen."),
      ],
    },
    {
      id: "time",
      title: "9. Datum und Uhrzeit",
      summary: "Heutiges Datum, Alter von Dateien und Wochentage.",
      blocks: [
        t("Zeiten sind in LocalFlow *Zeitstempel*: Anzahlen von Sekunden. Damit lässt sich leicht rechnen. `time.now()` ist die aktuelle Zeit:"),
        code('local now = time.now()\nlog("Sekunden seit 1970: " .. now)\nlog("In einer Stunde: " .. time.format("%H:%M", now + time.hours(1)))\n'),
        t("`time.format(...)` macht aus einem Zeitstempel lesbaren Text. `%Y` ist das Jahr, `%m` der Monat, `%d` der Tag, `%H:%M` die Uhrzeit und `%A` der Wochentag (auf Englisch):"),
        code('log(time.format())                   -- 2026-09-29 14:05:00\nlog(time.format("%d.%m.%Y"))         -- 29.09.2026\nlog(time.format("%A"))               -- Tuesday\nlog("Heute ist " .. time.today())    -- 2026-09-29\n'),
        t("`time.date()` zerlegt die Zeit in Teile, die Sie prüfen können, etwa `weekday` (1 = Montag, 7 = Sonntag):"),
        code('local d = time.date()\nif d.weekday >= 6 then\n    log("Wochenende!")\nelseif d.hour < 12 then\n    log("Guten Morgen")\nelse\n    log("Guten Tag")\nend\n'),
        t("`fs.modified(datei)` sagt Ihnen, wann eine Datei zuletzt geändert wurde. Zusammen mit `time.days(n)` finden Sie so alte Dateien:"),
        code('local cutoff = time.now() - time.days(30)\nlocal old = 0\n\nfor _, file in ipairs(fs.list("~/Downloads", "*")) do\n    if fs.modified(file) < cutoff then\n        old = old + 1\n    end\nend\n\nlog(old .. " Dateien in Downloads sind älter als 30 Tage")\n'),
      ],
    },
    {
      id: "watch",
      title: "10. Auf neue Dateien reagieren",
      summary: "Ausführen, sobald eine Datei in einem Ordner landet.",
      blocks: [
        t("Statt nach Zeitplan kann eine Automatisierung auf neue Dateien warten. Aktivieren Sie **Ausführen, wenn eine neue Datei in einem Ordner erscheint**, wählen Sie den Ordner (etwa `~/Downloads`) und optional die Dateien (etwa `*.pdf`)."),
        t("Jedes Mal, wenn eine passende Datei erscheint, läuft Ihre Automatisierung einmal, und `ctx.file` enthält den Pfad der neuen Datei. LocalFlow wartet, bis der Download fertig ist."),
        code('automation {\n    name = "Neue PDFs ablegen",\n\n    run = function(ctx)\n        if not ctx.file then\n            log("Keine neue Datei. Das läuft, sobald eine PDF erscheint.")\n            return\n        end\n\n        local folder = fs.join("~/Documents/PDF", time.format("%Y-%m"))\n        fs.move(ctx.file, fs.join(folder, fs.basename(ctx.file)))\n        notify(fs.basename(ctx.file) .. " abgelegt")\n    end\n}\n'),
        tip("Bei einem **Testlauf** gibt es keine neue Datei, deshalb ist `ctx.file` dann `nil`. Darum prüft das Beispiel das zuerst. Um es wirklich arbeiten zu sehen, speichern Sie und legen Sie eine Datei in den Ordner."),
        warning("Verschieben Sie keine Dateien *in* den überwachten Ordner. Das zählt als neue Datei und startet die Automatisierung erneut."),
      ],
    },
    {
      id: "errors",
      title: "11. Wenn etwas schiefgeht",
      summary: "Fehlermeldungen lesen und beheben.",
      blocks: [
        t("Fehler sehen so aus: `automation:5: attempt to call a nil value`. Die Zahl nach `automation:` ist die **Zeile**, in der es schiefging. Syntaxfehler markiert der Editor schon beim Tippen mit einem roten Punkt."),
        t("Unter häufigen Fehlern zeigt LocalFlow einen 💡-Hinweis. Die üblichen Verdächtigen:"),
        t("• **Fehlendes `end`**: jedes `if`, `for` und `function` braucht eines.\n• **Tippfehler**: `fs.lsit` statt `fs.list` oder `Log` statt `log` (Groß-/Kleinschreibung zählt).\n• **Mit nichts verbinden**: `\"Text\" .. x` scheitert, wenn `x` `nil` ist. Prüfen Sie, ob die Variable einen Wert hat.\n• **Fehlende Anführungszeichen**: Text steht in `\"doppelten Anführungszeichen\"`."),
        t("Wenn Sie nicht sicher sind, was in einer Variablen steht, protokollieren Sie sie:"),
        code('local files = fs.list("~/Downloads", "*.pdf")\nlog("Dateien: " .. #files)\nlog("erste: " .. tostring(files[1]))\n'),
        tip("Jeder Lauf wird im **Verlauf** mit Ausgabe und Fehler gespeichert, und das **Protokoll** zeigt alles, was Ihre Automatisierung geschrieben hat."),
      ],
    },
    {
      id: "tools",
      title: "12. Weitere Werkzeuge und Teilen",
      summary: "Speicher, Fragen, Systeminfos, das Web und Automatisierungen teilen.",
      blocks: [
        t("**Sich etwas merken.** Variablen gehen am Ende eines Laufs verloren. `store.set(schlüssel, wert)` speichert einen Wert für den nächsten Lauf, und `store.get(schlüssel, standard)` liest ihn wieder. (Testläufe beginnen immer mit leerem Speicher.)"),
        code('local runs = store.get("runs", 0) + 1\nstore.set("runs", runs)\nlog("Diese Automatisierung ist " .. runs .. "-mal gelaufen")\n'),
        t("**Erst fragen.** `ask(frage)` zeigt ein Ja/Nein-Fenster und wartet auf Ihre Antwort:"),
        code('if ask("Hallo sagen?") then\n    log("Hallo!")\nelse\n    log("OK, vielleicht später")\nend\n'),
        t("**Ihr Computer.** Die `system`-Funktionen verraten Ihnen etwas über Festplatten, Arbeitsspeicher, Akku und mehr:"),
        code('local gb = 1024 * 1024 * 1024\nlog("Computer: " .. system.computer_name())\nlog("Frei auf Ihrer Festplatte: " .. math.floor(system.disk_free() / gb) .. " GB")\nlocal m = system.memory()\nlog("Arbeitsspeicher belegt: " .. math.floor(m.used / m.total * 100) .. "%")\n'),
        t("**Textdateien und JSON.** `fs.write`, `fs.append` und `fs.read` arbeiten mit Textdateien. `json.encode` und `json.decode` wandeln zwischen Tabellen und JSON um, dem Format der meisten Webdienste:"),
        code('local file = "~/Documents/LocalFlow test.json"\nfs.write(file, json.encode({ saved = time.today(), items = { "a", "b" } }))\nlocal data = json.decode(fs.read(file))\nlog("Gespeichert am " .. data.saved .. " mit " .. #data.items .. " Einträgen")\n'),
        t("**Das Web.** `http.get(adresse)` lädt eine Seite oder fragt einen Webdienst nach Daten, und `http.post(adresse, { json = ... })` sendet Daten, zum Beispiel an einen Discord-Webhook:"),
        code('local r = http.get("https://api.github.com/repos/lua/lua")\nif r.ok then\n    local repo = json.decode(r.body)\n    log(repo.full_name .. " hat " .. repo.stargazers_count .. " Sterne")\nend\n', false),
        t("**Große Suchen.** `fs.largest(ordner, 20)` findet die größten Dateien, und `security.scan(ordner)` markiert Dateinamen, die nach Schadsoftware aussehen. Um eine ganze Festplatte zu durchsuchen, fügen Sie sie (etwa `C:\\`) unter **Einstellungen › Erlaubte Ordner** hinzu und erhöhen Sie **Einstellungen › Zeitlimit für Skripte** auf einige Minuten."),
        warning("`security.scan` prüft nur Datei*namen*. Es ist kein Virenscanner: Echte Schadsoftware kann beliebig heißen, und ein Treffer kann harmlos sein. Prüfen Sie Funde mit Ihrem Virenscanner."),
        t("**Teilen.** Klicken Sie bei einer Automatisierung auf **Exportieren**, um sie als `.localflow`-Datei zu speichern, und schicken Sie die Datei einem Freund. Er öffnet sie über **📥 Importieren** in der Seitenleiste, per Doppelklick oder indem er sie auf das LocalFlow-Fenster zieht."),
        tip("Importierte Automatisierungen kommen **ausgeschaltet** an, mit einer Liste dessen, was sie tun können (Dateien löschen, Apps öffnen, das Internet nutzen …). Lesen Sie den Code und machen Sie einen Testlauf, bevor Sie eine einschalten, und importieren Sie nur von Personen, denen Sie vertrauen."),
      ],
    },
    {
      id: "control",
      title: "13. Windows steuern",
      summary: "Befehle, Fenster, Tasten, Energie und weitere Auslöser.",
      blocks: [
        t("LocalFlow kann fast alles, was Sie selbst in Windows tun: Befehle ausführen, Fenster verschieben, Tasten drücken, den PC sperren oder herunterfahren. Weil das mächtig ist, funktionieren diese Funktionen nur in Automatisierungen, bei denen **Systemsteuerung erlauben** eingeschaltet ist (unter *Weitere Auslöser und Berechtigungen* über dem Code). Importierte Automatisierungen kommen immer mit ausgeschalteter Berechtigung an."),
        t("Schauen ist immer erlaubt. Das funktioniert in jeder Automatisierung:"),
        code("log(#process.list() .. \" Programme laufen\")\nlog(#window.list() .. \" Fenster sind offen\")\nlocal w, h = screen.size()\nlog(\"Bildschirm: \" .. w .. \" x \" .. h)\nlog(\"Inaktiv seit \" .. system.idle_seconds() .. \" Sekunden\")\n"),
        t("**Befehle.** `shell.run` führt einen Befehl wie die Eingabeaufforderung aus und liefert die Ausgabe; `shell.powershell` macht dasselbe mit PowerShell:"),
        code("local r = shell.run(\"ipconfig\")\nif r.ok then\n    log(r.output)\nend\n", false),
        t("**Fenster und Eingabe.** Ein Fenster finden, verschieben, nach vorne holen oder Tasten drücken und klicken:"),
        code("local notes = window.find(\"notepad\")\nif notes then\n    window.focus(notes)\n    keyboard.type(\"Von LocalFlow geschrieben\")\n    keyboard.press(\"ctrl+s\")\nend\n", false),
        t("**Energie.** `system.lock()`, `system.sleep()`, `system.shutdown(60)` (mit Zeit zum Abbrechen), Lautstärke, Helligkeit und Hintergrundbild. `system.wake_at(\"07:30\")` weckt den PC morgens aus dem Ruhezustand."),
        tip("**Weitere Auslöser.** Unter *Weitere Auslöser und Berechtigungen* kann eine Automatisierung auch per **Tastenkürzel** starten (etwa Strg+Alt+K), wenn eine **App startet oder schließt** (`ctx.app`), wenn der PC einige Minuten **inaktiv** ist oder wenn ein **USB-Laufwerk** angeschlossen wird (`ctx.drive`). Probieren Sie die Vorlagen *Fokusmodus*, *Sperren, wenn ich weggehe*, *Fenster anordnen* und *Fotos von der Speicherkarte importieren*."),
        warning("Schalten Sie **Systemsteuerung erlauben** nur für Skripte ein, die Sie verstehen. Ein solches Skript kann dasselbe wie Sie: Programme schließen, in jedes Fenster tippen oder den PC ausschalten."),
      ],
    },
    {
      id: "combine",
      title: "14. Automatisierungen kombinieren",
      summary: "Etwas Großes aus kleinen Schritten bauen, zum Beispiel ein VPN öffnen und dann das Land wählen.",
      blocks: [
        t("Große Aufgaben gelingen leichter mit mehreren kleinen Automatisierungen, die je eine Sache erledigen. Eine Haupt-Automatisierung führt sie dann mit `automations.call(name, daten)` der Reihe nach aus. Jeder Schritt lässt sich einzeln testen und in anderen Automatisierungen wiederverwenden."),
        t("**Schritt 1.** Speichere das als Automatisierung *Make project folder*. `ctx.input` enthält die übergebenen Daten, und was `run` zurückgibt, bekommt der Aufrufer:"),
        code('automation {\n    run = function(ctx)\n        local name = (ctx.input and ctx.input.name) or "New project"\n        local folder = fs.join("~/Documents/Projects", name)\n        fs.mkdir(folder)\n        log("Folder ready: " .. folder)\n        return { folder = folder }\n    end\n}\n', false),
        t("**Schritt 2.** Speichere das als *Write readme*. Es bekommt den Ordner aus Schritt 1:"),
        code('automation {\n    run = function(ctx)\n        local file = fs.join(ctx.input.folder, "README.txt")\n        fs.write(file, "Started on " .. time.today())\n        log("Wrote " .. file)\n    end\n}\n', false),
        t("**Die Haupt-Automatisierung** führt beide aus und gibt das Ergebnis von Schritt 1 an Schritt 2 weiter. Alles, was die Schritte protokollieren, erscheint in ihrem Protokoll, markiert mit dem Namen des Schritts:"),
        code('local project = automations.call("Make project folder", { name = "Holiday photos" })\nautomations.call("Write readme", project)\nnotify("Project ready: " .. project.folder)\n', false),
        t("`automations.call` stoppt alles, wenn ein Schritt fehlschlägt, meistens genau richtig. `automations.run` stoppt das Skript nie: Es liefert `ok`, `error` und `result`, und du entscheidest selbst. Zum Beispiel mit einem VPN: Der Schritt *Start VPN* ist nur `app.open(\"MyVPN\")`, und die Haupt-Automatisierung prüft, ob er geklappt hat, bevor sie ein Land wählt:"),
        code('local vpn = automations.run("Start VPN")\nif not vpn.ok then\n    notify("The VPN did not start: " .. vpn.error)\n    return\nend\nautomations.call("Choose VPN country", { country = "Germany" })\n', false),
        t("**Der Schritt *Choose VPN country*** tippt das Land ins VPN-Fenster. Dafür muss **Systemsteuerung erlauben** *in diesem Schritt* eingeschaltet sein, denn jeder Schritt behält seine eigene Einstellung. Programm- und Fensternamen sind nur Beispiele, nimm deine eigenen:"),
        code('automation {\n    run = function(ctx)\n        wait(5) -- give the VPN app time to open\n        local w = window.find("vpn") -- a word from your VPN window\'s title\n        if not w then\n            error("VPN window not found")\n        end\n        window.focus(w)\n        keyboard.type(ctx.input.country)\n        keyboard.press("enter")\n    end\n}\n', false),
        tip("**Ohne Code:** Unter *Weitere Auslöser und Berechtigungen* startet **Nach dieser Automatisierung ausführen** eine Automatisierung, wenn eine andere endet: nur wenn sie geklappt hat, nur bei einem Fehler oder so oder so. Was die erste zurückgegeben hat, kommt als `ctx.input` an, ihr Name als `ctx.previous`. Schritte kann man ausschalten: Eine ausgeschaltete Automatisierung startet nie von selbst, funktioniert aber als Schritt."),
        warning("Eine Automatisierung kann sich nicht selbst starten, auch nicht über andere Schritte, und Ketten stoppen nach 8 Automatisierungen hintereinander. Alle Schritte teilen sich das Zeitlimit der Haupt-Automatisierung; erhöhe für lange Ketten **Einstellungen › Zeitlimit für Skripte**."),
      ],
    },
    {
      id: "helpers",
      title: "15. Fertige Helfer",
      summary: "In Lua geschriebene Bibliotheken, Bilder, Tabellen, Passwörter und der Verlauf deines PCs.",
      blocks: [
        t("LocalFlow bringt Bibliotheken mit Helfern mit, geschrieben in Lua. Lade eine mit `require` am Anfang deines Skripts und nutze ihre Funktionen:"),
        code("local strings = require(\"lf.strings\")\nlocal paths = require(\"lf.paths\")\nlocal dates = require(\"lf.dates\")\n\nlog(strings.title(\"monthly report\"))          -- Monthly Report\nlog(paths.ext(\"C:/Photos/cat.JPG\"))           -- jpg\nlog(paths.size_text(1536))                    -- 1.5 KB\nlog(dates.weekday_name(time.now()))\nlog(dates.duration(3725))                     -- 1 h 2 min 5 s\n"),
        t("• **lf.strings**: `trim`, `split`, `contains`, `replace`, `title`, `slug`, `pad_left`, `number`, ...\n• **lf.tables**: `map`, `filter`, `sort_by`, `group_by`, `unique`, `sum`, `dump`, ...\n• **lf.paths**: `ext`, `stem`, `with_ext`, `safe_name`, `unique`, `size_text`, ...\n• **lf.dates**: `add_days`, `add_months`, `days_between`, `week_number`, `ago`, ...\n• **lf.retry**: erneut versuchen, auf etwas warten, höchstens alle paar Stunden warnen\n• **lf.template**, **lf.report**: Text ausfüllen, saubere Berichte bauen\n• **lf.test**: eigenen Code prüfen"),
        t("**Listen leicht gemacht.** `lf.tables` arbeitet mit den Listen, die Funktionen wie `fs.list` liefern:"),
        code("local tables = require(\"lf.tables\")\nlocal paths = require(\"lf.paths\")\n\nlocal files = fs.list(\"~/Downloads\", \"*\")\nlocal biggest = tables.take(tables.sort_by(files, fs.size, true), 3)\nfor _, file in ipairs(biggest) do\n    log(paths.name(file) .. \"  \" .. paths.size_text(fs.size(file)))\nend\n"),
        t("**Bilder.** `image.resize` macht kleinere Kopien, `image.convert` ändert das Format, und `image.taken` verrät, wann ein Foto aufgenommen wurde. **Tabellen.** `csv.read` und `csv.write` arbeiten mit CSV-Dateien, die Excel öffnet:"),
        code("local rows = {}\nfor _, file in ipairs(fs.list(\"~/Downloads\", \"*\")) do\n    rows[#rows + 1] = { name = fs.basename(file), bytes = fs.size(file) }\nend\ncsv.write(\"~/Documents/downloads.csv\", rows, { header = { \"name\", \"bytes\" } })\nlog(\"Saved \" .. #rows .. \" rows\")\n"),
        t("**Der Verlauf deines PCs.** Solange LocalFlow läuft, notiert es jede Minute die Auslastung von Prozessor, Speicher, Festplatte und Akku (das Diagramm siehst du auf der Übersichtsseite). Skripte können Durchschnitte und Spitzen abfragen:"),
        code("local cpu = metrics.average(\"cpu\", 60)\nif cpu then\n    log(string.format(\"CPU over the last hour: %.0f%% on average, %.0f%% at most\", cpu, metrics.peak(\"cpu\", 60)))\nelse\n    log(\"No history yet, try again in a minute\")\nend\n"),
        warning("`crypto.encrypt` sperrt Dateien mit einem Passwort. Ohne das Passwort gibt es keinen Weg zurück: Bewahre es sicher auf und behalte das Original, bis du geprüft hast, dass sich die gesperrte Kopie öffnen lässt."),
        tip("Probiere die Vorlagen *Doppelte Dateien finden*, *Fotos nach Aufnahmedatum sortieren*, *Wöchentlicher Downloads-Bericht*, *Monatliche Ausgabenübersicht* und *PC-Gesundheitscheck*: Jede nutzt diese Helfer, und sie zu lesen ist eine gute Übung."),
      ],
    },
  ],

  hints: {
    fieldCall: (m, fs) => `Dort gibt es keine Funktion namens \`${m[1]}\`. Prüfen Sie die Schreibweise. Verfügbar: ${fs}.`,
    blockedGlobal: (m) => `\`${m[1]}\` ist in LocalFlow aus Sicherheitsgründen nicht verfügbar. Verwenden Sie für Dateien die \`fs.*\`-Funktionen.`,
    globalCall: (m) => `\`${m[1]}\` ist keine bekannte Funktion. Prüfen Sie die Schreibweise (Groß-/Kleinschreibung zählt) oder definieren Sie sie mit \`local function ${m[1]}() ... end\` *oberhalb* der Zeile, die sie verwendet.`,
    nilValue: (m) => `\`${m[1]}\` hat hier keinen Wert. Vielleicht ein Tippfehler, oder die Variable wurde nie mit \`local ${m[1]} = ...\` gesetzt.`,
    concatNil: (m) => `Sie verbinden Text mit \`..\`, aber ${m[1] ? `\`${m[1]}\`` : "einer der Werte"} ist \`nil\` (leer). Sorgen Sie für einen Wert oder verwenden Sie \`tostring(...)\`.`,
    concatType: (m) => `Eine ${m[1] === "table" ? "Tabelle" : "Wahrheitswert-Variable"} lässt sich nicht direkt mit \`..\` verbinden. Verpacken Sie sie: \`tostring(wert)\`${m[1] === "table" ? " oder verwenden Sie `#liste` für die Anzahl" : ""}.`,
    arith: () => "Sie rechnen oder vergleichen mit etwas, das keine Zahl ist (oder `nil`). Protokollieren Sie die Werte, um sie zu prüfen.",
    missingEnd: () => "Ein `end` fehlt. Jedes `if`, `for`, `while` und `function` braucht sein eigenes `end`.",
    missingThen: () => "`if` braucht nach der Bedingung ein `then`: `if x > 1 then ... end`. Zum Vergleichen `==` verwenden, nicht `=`.",
    missingDo: () => "Schleifen brauchen `do`: `for _, file in ipairs(files) do ... end`.",
    missingEquals: () => "Lua hat das als Zuweisung gelesen. Prüfen Sie auf ein falsch geschriebenes Schlüsselwort oder eine fehlende `(` bei einem Funktionsaufruf.",
    unfinishedString: () => "Einem Text fehlt das schließende Anführungszeichen `\"`.",
    missingBrace: () => "Einer `{` fehlt die schließende `}`. Prüfen Sie auch die Kommas zwischen Einträgen, etwa `name = \"x\",`.",
    missingParen: () => "Einer `(` fehlt die schließende `)`. Prüfen Sie auch, ob beim Verbinden von Text ein `..` fehlt.",
    unexpectedSymbol: () => "Lua hat diese Zeile nicht verstanden. Suchen Sie nach fehlenden Anführungszeichen, `..` zwischen Texten, Kommas oder `then`/`do`.",
    accessDenied: () => "Skripte dürfen nur Dateien in Ihren erlaubten Ordnern verwenden. Prüfen Sie den Pfad oder fügen Sie den Ordner in den Einstellungen hinzu.",
    notFound: () => "Diesen Pfad gibt es nicht. Denken Sie daran: `~` ist Ihr Benutzerordner. Prüfen Sie vorher mit `fs.exists(pfad)`.",
    destExists: () => "`fs.move` überschreibt nie. Prüfen Sie vorher mit `fs.exists(target)` und überspringen oder benennen Sie um.",
    timedOut: () => "Das Skript lief zu lange, meist wegen einer Schleife, die nie endet. Prüfen Sie Ihre `while`-Schleifen. Für große Suchen erhöhen Sie **Einstellungen › Zeitlimit für Skripte**.",
    missingRun: () => "Fügen Sie `run = function(ctx) ... end` in `automation { ... }` ein.",
    appNotFound: () => "Verwenden Sie den Namen aus dem Startmenü, etwa `\"Spotify\"`. Führen Sie `app.shortcuts()` (oder die Vorlage *Meine Apps anzeigen*) aus, um alle Namen zu sehen, oder geben Sie den vollständigen Pfad zur .exe an.",
    timeLimit: () => "Skripte müssen innerhalb ihres Zeitlimits fertig sein, inklusive `wait(...)`. Verwenden Sie kürzere Wartezeiten oder erhöhen Sie **Einstellungen › Zeitlimit für Skripte**.",
    stepMissing: () => "Schreib den Namen genau wie in der Seitenleiste (Groß- und Kleinschreibung ist egal) oder führe `automations.list()` aus, um alle Namen zu sehen.",
    badArgument: () => "Eine Funktion hat einen falschen Werttyp bekommen, oft fehlt ein Argument oder es steht eine Zahl, wo Text erwartet wird.",
  },
};
